// Additional project ideas to make it easier to unlock achievements
import type { ProjectIdea } from "./project-ideas"

export const additionalProjectIdeas: ProjectIdea[] = [
  // Modern Web Frameworks
  {
    titulo: "Blog con Astro",
    descripcion: "Crea un blog estático con Astro y Markdown para contenido.",
    categoria: "Web",
    tecnologias: ["Astro", "TypeScript"],
    frameworks: ["Tailwind CSS"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación SvelteKit con Autenticación",
    descripcion: "Desarrolla una aplicación web con SvelteKit y autenticación de usuarios.",
    categoria: "Web",
    tecnologias: ["Svelte", "TypeScript"],
    frameworks: ["SvelteKit"],
    basesdedatos: ["Supabase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Dashboard con Qwik",
    descripcion: "Crea un dashboard interactivo con Qwik y visualización de datos.",
    categoria: "Web",
    tecnologias: ["Qwik", "TypeScript"],
    frameworks: ["Tailwind CSS"],
    basesdedatos: ["Supabase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Notas con SolidJS",
    descripcion: "Desarrolla una aplicación de notas con SolidJS y almacenamiento local.",
    categoria: "Web",
    tecnologias: ["SolidJS", "TypeScript"],
    frameworks: ["Tailwind CSS"],
    basesdedatos: ["IndexedDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "E-commerce con Remix",
    descripcion: "Crea una tienda en línea con Remix y gestión de productos.",
    categoria: "E-commerce",
    tecnologias: ["Remix", "TypeScript"],
    frameworks: ["Tailwind CSS"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación HTMX con Django",
    descripcion: "Desarrolla una aplicación web interactiva usando HTMX y Django.",
    categoria: "Web",
    tecnologias: ["HTMX", "Python"],
    frameworks: ["Django"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },

  // Modern Runtimes
  {
    titulo: "API REST con Deno",
    descripcion: "Crea una API REST completa usando Deno y Oak.",
    categoria: "Backend",
    tecnologias: ["Deno", "TypeScript"],
    frameworks: ["Oak"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Servidor Web con Bun",
    descripcion: "Desarrolla un servidor web rápido con Bun y Elysia.",
    categoria: "Backend",
    tecnologias: ["Bun", "TypeScript"],
    frameworks: ["Elysia"],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },

  // Functional Programming
  {
    titulo: "Aplicación Web con Elm",
    descripcion: "Crea una aplicación web frontend usando el lenguaje funcional Elm.",
    categoria: "Web",
    tecnologias: ["Elm"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación Web con ReScript y React",
    descripcion: "Desarrolla una aplicación web usando ReScript con React.",
    categoria: "Web",
    tecnologias: ["ReScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },

  // Modern Databases
  {
    titulo: "Aplicación con Supabase",
    descripcion: "Crea una aplicación web completa usando Supabase para autenticación y base de datos.",
    categoria: "Web",
    tecnologias: ["TypeScript"],
    frameworks: ["Next.js"],
    basesdedatos: ["Supabase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Blog con PlanetScale",
    descripcion: "Desarrolla un blog con Next.js y PlanetScale como base de datos.",
    categoria: "Web",
    tecnologias: ["TypeScript"],
    frameworks: ["Next.js"],
    basesdedatos: ["PlanetScale"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación con Neon Database",
    descripcion: "Crea una aplicación web usando Neon como base de datos PostgreSQL serverless.",
    categoria: "Web",
    tecnologias: ["TypeScript"],
    frameworks: ["Next.js"],
    basesdedatos: ["Neon"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Chat en Tiempo Real con Upstash",
    descripcion: "Desarrolla un chat en tiempo real usando Upstash Redis.",
    categoria: "Comunicación",
    tecnologias: ["TypeScript"],
    frameworks: ["Next.js"],
    basesdedatos: ["Upstash"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación con Turso",
    descripcion: "Crea una aplicación web con Turso como base de datos SQLite distribuida.",
    categoria: "Web",
    tecnologias: ["TypeScript"],
    frameworks: ["SvelteKit"],
    basesdedatos: ["Turso"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },

  // Brainfuck projects (for easter egg)
  {
    titulo: "Hola Mundo en Brainfuck",
    descripcion: "Implementa un programa 'Hola Mundo' en Brainfuck.",
    categoria: "Programación Esotérica",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Calculadora Simple en Brainfuck",
    descripcion: "Crea una calculadora que pueda sumar dos números de un solo dígito en Brainfuck.",
    categoria: "Programación Esotérica",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Generador de ASCII Art en Brainfuck",
    descripcion: "Desarrolla un programa que genere un patrón simple de ASCII art en Brainfuck.",
    categoria: "Programación Esotérica",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Consola",
  },
]
