import type { ProjectIdea } from "./project-ideas"

// New languages to add: Astro, Svelte, Deno, Bun, Elm, Reason/ReScript, SolidJS, Qwik, Remix, Htmx

export const additionalLanguagesTwo: ProjectIdea[] = [
  // Astro Projects
  {
    titulo: "Blog Personal con Astro",
    descripcion: "Un blog personal con contenido estático y optimizado para SEO usando Astro.",
    categoria: "Web",
    tecnologias: ["Astro", "JavaScript"],
    frameworks: ["Tailwind CSS"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Portafolio de Desarrollador con Astro",
    descripcion: "Un sitio web de portafolio para mostrar proyectos y habilidades, con páginas estáticas rápidas.",
    categoria: "Web",
    tecnologias: ["Astro", "TypeScript"],
    frameworks: ["Tailwind CSS"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sitio de Documentación con Astro",
    descripcion: "Un sitio de documentación técnica con navegación por secciones y búsqueda integrada.",
    categoria: "Documentación",
    tecnologias: ["Astro", "JavaScript"],
    frameworks: ["Tailwind CSS"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Landing Page para Producto con Astro",
    descripcion: "Una landing page de alto rendimiento para promocionar un producto o servicio.",
    categoria: "Marketing",
    tecnologias: ["Astro", "JavaScript"],
    frameworks: ["Tailwind CSS"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Blog Corporativo con Astro y CMS",
    descripcion: "Un blog corporativo que utiliza Astro para el frontend y un CMS headless para el contenido.",
    categoria: "Contenido",
    tecnologias: ["Astro", "TypeScript"],
    frameworks: ["Tailwind CSS"],
    basesdedatos: ["Strapi"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Tienda Online con Astro y Shopify",
    descripcion: "Una tienda online que utiliza Astro para el frontend y Shopify como backend de e-commerce.",
    categoria: "E-commerce",
    tecnologias: ["Astro", "TypeScript"],
    frameworks: ["Tailwind CSS", "React"],
    basesdedatos: ["Shopify"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Cursos con Astro y React",
    descripcion:
      "Una plataforma educativa que combina páginas estáticas de Astro con componentes interactivos de React.",
    categoria: "Educación",
    tecnologias: ["Astro", "TypeScript"],
    frameworks: ["React", "Tailwind CSS"],
    basesdedatos: ["Supabase"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sitio Multi-idioma con Astro",
    descripcion: "Un sitio web corporativo con soporte para múltiples idiomas y optimización SEO avanzada.",
    categoria: "Corporativo",
    tecnologias: ["Astro", "TypeScript"],
    frameworks: ["Tailwind CSS"],
    basesdedatos: ["Prisma", "PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Svelte Projects
  {
    titulo: "Lista de Tareas con Svelte",
    descripcion: "Una aplicación simple de lista de tareas con Svelte para gestionar actividades diarias.",
    categoria: "Productividad",
    tecnologias: ["Svelte", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Calculadora Interactiva con Svelte",
    descripcion: "Una calculadora con animaciones fluidas y reactividad instantánea usando Svelte.",
    categoria: "Utilidad",
    tecnologias: ["Svelte", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Dashboard Personal con Svelte",
    descripcion: "Un dashboard personal para seguimiento de hábitos, clima y noticias con widgets personalizables.",
    categoria: "Productividad",
    tecnologias: ["Svelte", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Memoria con Svelte",
    descripcion: "Un juego de memoria con tarjetas y animaciones fluidas implementado con Svelte.",
    categoria: "Juego",
    tecnologias: ["Svelte", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Notas con SvelteKit",
    descripcion: "Una aplicación de notas con sincronización en la nube y editor markdown usando SvelteKit.",
    categoria: "Productividad",
    tecnologias: ["Svelte", "TypeScript"],
    frameworks: ["SvelteKit"],
    basesdedatos: ["Firebase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Red Social para Desarrolladores con SvelteKit",
    descripcion: "Una red social para desarrolladores con perfiles, publicaciones y mensajería usando SvelteKit.",
    categoria: "Red Social",
    tecnologias: ["Svelte", "TypeScript"],
    frameworks: ["SvelteKit"],
    basesdedatos: ["Supabase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Streaming de Audio con Svelte",
    descripcion: "Una plataforma para streaming de podcasts y música con reproductor personalizado en Svelte.",
    categoria: "Multimedia",
    tecnologias: ["Svelte", "TypeScript"],
    frameworks: ["SvelteKit"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Editor de Código Colaborativo con Svelte",
    descripcion:
      "Un editor de código en tiempo real para colaboración entre desarrolladores usando Svelte y WebSockets.",
    categoria: "Desarrollo",
    tecnologias: ["Svelte", "TypeScript"],
    frameworks: ["SvelteKit"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Deno Projects
  {
    titulo: "API REST Simple con Deno",
    descripcion: "Una API REST básica implementada con Deno y Oak para gestionar una colección de datos.",
    categoria: "Backend",
    tecnologias: ["Deno", "TypeScript"],
    frameworks: ["Oak"],
    basesdedatos: ["JSON"],
    nivel: "Student",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "CLI para Gestión de Tareas con Deno",
    descripcion: "Una herramienta de línea de comandos para gestionar tareas diarias implementada con Deno.",
    categoria: "Utilidad",
    tecnologias: ["Deno", "TypeScript"],
    frameworks: [],
    basesdedatos: ["JSON"],
    nivel: "Student",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Servidor de Archivos con Deno",
    descripcion: "Un servidor para compartir archivos en red local con interfaz web implementado con Deno.",
    categoria: "Utilidad",
    tecnologias: ["Deno", "TypeScript"],
    frameworks: ["Oak"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Bot de Discord con Deno",
    descripcion: "Un bot para Discord con comandos personalizados implementado con Deno.",
    categoria: "Comunicación",
    tecnologias: ["Deno", "TypeScript"],
    frameworks: [],
    basesdedatos: ["JSON"],
    nivel: "Trainee",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "API de Microservicios con Deno",
    descripcion: "Una arquitectura de microservicios implementada con Deno y comunicación entre servicios.",
    categoria: "Backend",
    tecnologias: ["Deno", "TypeScript"],
    frameworks: ["Oak"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Autenticación con Deno",
    descripcion: "Un sistema completo de autenticación y autorización implementado con Deno y JWT.",
    categoria: "Seguridad",
    tecnologias: ["Deno", "TypeScript"],
    frameworks: ["Oak"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Análisis de Datos con Deno",
    descripcion: "Una plataforma para procesar y visualizar grandes conjuntos de datos con Deno y WebSockets.",
    categoria: "Análisis de Datos",
    tecnologias: ["Deno", "TypeScript"],
    frameworks: ["Fresh"],
    basesdedatos: ["InfluxDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Contenido con Deno",
    descripcion: "Un CMS completo con editor WYSIWYG y gestión de usuarios implementado con Deno.",
    categoria: "Contenido",
    tecnologias: ["Deno", "TypeScript"],
    frameworks: ["Fresh"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Bun Projects
  {
    titulo: "Servidor HTTP Simple con Bun",
    descripcion: "Un servidor HTTP básico implementado con Bun para servir contenido estático.",
    categoria: "Backend",
    tecnologias: ["Bun", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Generador de Imágenes con Bun",
    descripcion: "Una herramienta para generar y manipular imágenes utilizando Bun y sus APIs nativas.",
    categoria: "Utilidad",
    tecnologias: ["Bun", "TypeScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "API REST con Bun y Elysia",
    descripcion: "Una API REST implementada con Bun y el framework Elysia para alto rendimiento.",
    categoria: "Backend",
    tecnologias: ["Bun", "TypeScript"],
    frameworks: ["Elysia"],
    basesdedatos: ["SQLite"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Procesador de Archivos CSV con Bun",
    descripcion: "Una herramienta para procesar y transformar archivos CSV de gran tamaño con Bun.",
    categoria: "Utilidad",
    tecnologias: ["Bun", "TypeScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Servidor de WebSockets con Bun",
    descripcion: "Un servidor de WebSockets de alto rendimiento para aplicaciones en tiempo real con Bun.",
    categoria: "Backend",
    tecnologias: ["Bun", "TypeScript"],
    frameworks: ["Elysia"],
    basesdedatos: ["Redis"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "API GraphQL con Bun",
    descripcion: "Una API GraphQL completa con resolvers y tipos implementada con Bun.",
    categoria: "Backend",
    tecnologias: ["Bun", "TypeScript"],
    frameworks: ["Elysia"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Procesamiento de Colas con Bun",
    descripcion: "Un sistema de procesamiento de tareas en segundo plano con colas y workers usando Bun.",
    categoria: "Backend",
    tecnologias: ["Bun", "TypeScript"],
    frameworks: [],
    basesdedatos: ["Redis"],
    nivel: "Senior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Plataforma de Streaming de Video con Bun",
    descripcion: "Una plataforma para streaming de video con transcodificación en tiempo real usando Bun.",
    categoria: "Multimedia",
    tecnologias: ["Bun", "TypeScript"],
    frameworks: ["Elysia", "React"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Elm Projects
  {
    titulo: "Calculadora Funcional con Elm",
    descripcion: "Una calculadora implementada con programación funcional pura usando Elm.",
    categoria: "Utilidad",
    tecnologias: ["Elm"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Preguntas y Respuestas con Elm",
    descripcion: "Un juego de trivia implementado con Elm para demostrar arquitectura funcional.",
    categoria: "Juego",
    tecnologias: ["Elm"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Clima con Elm",
    descripcion: "Una aplicación para consultar el clima que demuestra manejo de efectos en Elm.",
    categoria: "Utilidad",
    tecnologias: ["Elm"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Editor de Markdown con Elm",
    descripcion: "Un editor de Markdown con vista previa en tiempo real implementado con Elm.",
    categoria: "Productividad",
    tecnologias: ["Elm"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Gestión de Proyectos con Elm",
    descripcion: "Una aplicación para gestionar proyectos y tareas implementada con arquitectura Elm.",
    categoria: "Productividad",
    tecnologias: ["Elm"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Dashboard de Analíticas con Elm",
    descripcion: "Un dashboard para visualizar datos y estadísticas con gráficos implementado en Elm.",
    categoria: "Análisis de Datos",
    tecnologias: ["Elm"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Comercio Electrónico con Elm",
    descripcion: "Una tienda online completa implementada con arquitectura Elm y gestión de estado.",
    categoria: "E-commerce",
    tecnologias: ["Elm"],
    frameworks: [],
    basesdedatos: ["GraphQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Editor de Diagramas con Elm",
    descripcion: "Un editor de diagramas y gráficos vectoriales implementado con Elm.",
    categoria: "Productividad",
    tecnologias: ["Elm"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // ReScript/Reason Projects
  {
    titulo: "Lista de Tareas con ReScript",
    descripcion: "Una aplicación simple de lista de tareas implementada con ReScript y React.",
    categoria: "Productividad",
    tecnologias: ["ReScript"],
    frameworks: ["React"],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Memoria con ReScript",
    descripcion: "Un juego de memoria con tarjetas implementado con ReScript y React.",
    categoria: "Juego",
    tecnologias: ["ReScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Notas con ReScript",
    descripcion: "Una aplicación para tomar notas con categorías implementada con ReScript y React.",
    categoria: "Productividad",
    tecnologias: ["ReScript"],
    frameworks: ["React"],
    basesdedatos: ["LocalStorage"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Buscador de Películas con ReScript",
    descripcion: "Una aplicación para buscar información de películas implementada con ReScript y React.",
    categoria: "Entretenimiento",
    tecnologias: ["ReScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Chat con ReScript",
    descripcion: "Una aplicación de chat en tiempo real implementada con ReScript, React y WebSockets.",
    categoria: "Comunicación",
    tecnologias: ["ReScript"],
    frameworks: ["React"],
    basesdedatos: ["Firebase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Editor de Código con ReScript",
    descripcion: "Un editor de código con resaltado de sintaxis implementado con ReScript y React.",
    categoria: "Desarrollo",
    tecnologias: ["ReScript"],
    frameworks: ["React"],
    basesdedatos: ["IndexedDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Trading con ReScript",
    descripcion: "Una plataforma para trading de criptomonedas implementada con ReScript y React.",
    categoria: "Finanzas",
    tecnologias: ["ReScript"],
    frameworks: ["React"],
    basesdedatos: ["GraphQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Editor de Gráficos Vectoriales con ReScript",
    descripcion: "Un editor de gráficos vectoriales implementado con ReScript y Canvas API.",
    categoria: "Diseño",
    tecnologias: ["ReScript"],
    frameworks: ["React"],
    basesdedatos: ["IndexedDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // SolidJS Projects
  {
    titulo: "Lista de Tareas con SolidJS",
    descripcion: "Una aplicación simple de lista de tareas implementada con SolidJS.",
    categoria: "Productividad",
    tecnologias: ["SolidJS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Calculadora Reactiva con SolidJS",
    descripcion: "Una calculadora con reactividad fina implementada con SolidJS.",
    categoria: "Utilidad",
    tecnologias: ["SolidJS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Clima con SolidJS",
    descripcion: "Una aplicación para consultar el clima implementada con SolidJS y APIs externas.",
    categoria: "Utilidad",
    tecnologias: ["SolidJS", "TypeScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Preguntas con SolidJS",
    descripcion: "Un juego de preguntas y respuestas implementado con SolidJS y reactividad.",
    categoria: "Juego",
    tecnologias: ["SolidJS", "TypeScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Notas con SolidJS",
    descripcion: "Una aplicación para tomar notas con etiquetas implementada con SolidJS y SolidStart.",
    categoria: "Productividad",
    tecnologias: ["SolidJS", "TypeScript"],
    frameworks: ["SolidStart"],
    basesdedatos: ["IndexedDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Dashboard de Analíticas con SolidJS",
    descripcion: "Un dashboard para visualizar datos con gráficos implementado con SolidJS.",
    categoria: "Análisis de Datos",
    tecnologias: ["SolidJS", "TypeScript"],
    frameworks: ["SolidStart"],
    basesdedatos: ["Supabase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Streaming de Video con SolidJS",
    descripcion: "Una plataforma para streaming de video implementada con SolidJS y WebRTC.",
    categoria: "Multimedia",
    tecnologias: ["SolidJS", "TypeScript"],
    frameworks: ["SolidStart"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Editor de Documentos Colaborativo con SolidJS",
    descripcion: "Un editor de documentos en tiempo real para colaboración implementado con SolidJS.",
    categoria: "Productividad",
    tecnologias: ["SolidJS", "TypeScript"],
    frameworks: ["SolidStart"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Qwik Projects
  {
    titulo: "Landing Page con Qwik",
    descripcion: "Una landing page de alto rendimiento implementada con Qwik para carga instantánea.",
    categoria: "Marketing",
    tecnologias: ["Qwik", "TypeScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Blog Personal con Qwik",
    descripcion: "Un blog personal implementado con Qwik para máximo rendimiento y SEO.",
    categoria: "Contenido",
    tecnologias: ["Qwik", "TypeScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Recetas con Qwik",
    descripcion: "Una aplicación para buscar y guardar recetas implementada con Qwik City.",
    categoria: "Estilo de Vida",
    tecnologias: ["Qwik", "TypeScript"],
    frameworks: ["Qwik City"],
    basesdedatos: ["Supabase"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Tienda Online con Qwik",
    descripcion: "Una tienda online implementada con Qwik para carga instantánea y mejor conversión.",
    categoria: "E-commerce",
    tecnologias: ["Qwik", "TypeScript"],
    frameworks: ["Qwik City"],
    basesdedatos: ["Supabase"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Redes Sociales con Qwik",
    descripcion: "Una aplicación de redes sociales implementada con Qwik para interacción instantánea.",
    categoria: "Red Social",
    tecnologias: ["Qwik", "TypeScript"],
    frameworks: ["Qwik City"],
    basesdedatos: ["Supabase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Dashboard Empresarial con Qwik",
    descripcion: "Un dashboard empresarial con gráficos y análisis implementado con Qwik.",
    categoria: "Empresarial",
    tecnologias: ["Qwik", "TypeScript"],
    frameworks: ["Qwik City"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Cursos Online con Qwik",
    descripcion: "Una plataforma educativa con cursos y evaluaciones implementada con Qwik.",
    categoria: "Educación",
    tecnologias: ["Qwik", "TypeScript"],
    frameworks: ["Qwik City"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Contenido con Qwik",
    descripcion: "Un CMS completo implementado con Qwik para edición y publicación de contenido.",
    categoria: "Contenido",
    tecnologias: ["Qwik", "TypeScript"],
    frameworks: ["Qwik City"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Remix Projects
  {
    titulo: "Blog Personal con Remix",
    descripcion: "Un blog personal implementado con Remix para mejor rendimiento y SEO.",
    categoria: "Contenido",
    tecnologias: ["Remix", "TypeScript"],
    frameworks: [],
    basesdedatos: ["SQLite"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Notas con Remix",
    descripcion: "Una aplicación para tomar notas implementada con Remix y su modelo de datos.",
    categoria: "Productividad",
    tecnologias: ["Remix", "TypeScript"],
    frameworks: [],
    basesdedatos: ["SQLite"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Recetas con Remix",
    descripcion: "Una aplicación para buscar y guardar recetas implementada con Remix.",
    categoria: "Estilo de Vida",
    tecnologias: ["Remix", "TypeScript"],
    frameworks: [],
    basesdedatos: ["Prisma", "SQLite"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Tienda Online con Remix",
    descripcion: "Una tienda online implementada con Remix para mejor experiencia de usuario.",
    categoria: "E-commerce",
    tecnologias: ["Remix", "TypeScript"],
    frameworks: [],
    basesdedatos: ["Prisma", "PostgreSQL"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Gestión de Proyectos con Remix",
    descripcion: "Una aplicación para gestionar proyectos y tareas implementada con Remix.",
    categoria: "Productividad",
    tecnologias: ["Remix", "TypeScript"],
    frameworks: [],
    basesdedatos: ["Prisma", "PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Red Social para Desarrolladores con Remix",
    descripcion: "Una red social para desarrolladores implementada con Remix y su modelo de datos.",
    categoria: "Red Social",
    tecnologias: ["Remix", "TypeScript"],
    frameworks: [],
    basesdedatos: ["Prisma", "PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Cursos Online con Remix",
    descripcion: "Una plataforma educativa con cursos y evaluaciones implementada con Remix.",
    categoria: "Educación",
    tecnologias: ["Remix", "TypeScript"],
    frameworks: [],
    basesdedatos: ["Prisma", "PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Contenido con Remix",
    descripcion: "Un CMS completo implementado con Remix para edición y publicación de contenido.",
    categoria: "Contenido",
    tecnologias: ["Remix", "TypeScript"],
    frameworks: [],
    basesdedatos: ["Prisma", "PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // HTMX Projects
  {
    titulo: "Formulario Interactivo con HTMX",
    descripcion: "Un formulario con validación y feedback instantáneo implementado con HTMX.",
    categoria: "Web",
    tecnologias: ["HTMX", "HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Lista de Tareas con HTMX",
    descripcion: "Una aplicación de lista de tareas con interacciones dinámicas usando HTMX.",
    categoria: "Productividad",
    tecnologias: ["HTMX", "HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Buscador en Tiempo Real con HTMX",
    descripcion: "Un buscador que muestra resultados en tiempo real mientras el usuario escribe usando HTMX.",
    categoria: "Utilidad",
    tecnologias: ["HTMX", "HTML", "CSS", "JavaScript"],
    frameworks: ["Flask"],
    basesdedatos: ["SQLite"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Chat con HTMX",
    descripcion: "Una aplicación de chat simple con actualizaciones en tiempo real usando HTMX y SSE.",
    categoria: "Comunicación",
    tecnologias: ["HTMX", "HTML", "CSS", "JavaScript"],
    frameworks: ["Flask"],
    basesdedatos: ["SQLite"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Dashboard Interactivo con HTMX",
    descripcion: "Un dashboard con gráficos y tablas actualizables sin recargar la página usando HTMX.",
    categoria: "Análisis de Datos",
    tecnologias: ["HTMX", "HTML", "CSS", "JavaScript"],
    frameworks: ["Django"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Inventario con HTMX",
    descripcion: "Un sistema para gestionar inventario con interacciones fluidas usando HTMX.",
    categoria: "Negocios",
    tecnologias: ["HTMX", "HTML", "CSS", "JavaScript"],
    frameworks: ["Django"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Comercio Electrónico con HTMX",
    descripcion: "Una tienda online completa con carrito de compras dinámico usando HTMX.",
    categoria: "E-commerce",
    tecnologias: ["HTMX", "HTML", "CSS", "JavaScript"],
    frameworks: ["Django"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Contenido con HTMX",
    descripcion: "Un CMS con edición en línea y publicación instantánea usando HTMX.",
    categoria: "Contenido",
    tecnologias: ["HTMX", "HTML", "CSS", "JavaScript"],
    frameworks: ["Django"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
]
