// Asegurarse de que Brainfuck esté incluido en los datos y sea accesible

// Verificar que los proyectos de Brainfuck estén correctamente definidos
// (No es necesario modificar esto si ya está correcto en el código)

// Añadir un comentario al inicio del archivo para confirmar que Brainfuck está incluido
// Definir tipos
import type { ProjectIdea } from "./project-ideas"

// Lista adicional de ideas con más lenguajes de programación
// Incluye Brainfuck como easter egg (activable con el código "bf")
export const additionalLanguageIdeas: ProjectIdea[] = [
  // Rust - 8 proyectos
  {
    titulo: "CLI para Gestión de Tareas",
    descripcion: "Herramienta de línea de comandos para gestionar tareas diarias con almacenamiento local.",
    categoria: "Productividad",
    tecnologias: ["Rust"],
    frameworks: ["clap"],
    basesdedatos: ["SQLite"],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Servidor Web de Alto Rendimiento",
    descripcion: "Implementación de un servidor web ligero y de alto rendimiento con manejo asíncrono de conexiones.",
    categoria: "Web",
    tecnologias: ["Rust"],
    frameworks: ["Tokio", "Hyper"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Analizador de Archivos de Log",
    descripcion: "Herramienta para analizar y extraer estadísticas de archivos de registro con procesamiento paralelo.",
    categoria: "Utilidad",
    tecnologias: ["Rust"],
    frameworks: ["Rayon"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "API REST con Autenticación",
    descripcion: "Servicio web RESTful con autenticación JWT y manejo eficiente de recursos.",
    categoria: "Web",
    tecnologias: ["Rust"],
    frameworks: ["Actix-web", "Diesel"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Emulador de Sistema Retro",
    descripcion: "Emulador de una consola o computadora retro con enfoque en precisión y rendimiento.",
    categoria: "Sistemas",
    tecnologias: ["Rust"],
    frameworks: ["SDL2"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego 2D Simple",
    descripcion: "Videojuego 2D con física básica, gráficos y sistema de puntuación.",
    categoria: "Juego",
    tecnologias: ["Rust"],
    frameworks: ["ggez", "Bevy"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Compilador para Lenguaje Simple",
    descripcion: "Compilador para un lenguaje de programación minimalista con generación de código nativo.",
    categoria: "Desarrollo",
    tecnologias: ["Rust"],
    frameworks: ["LLVM"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Cliente BitTorrent",
    descripcion: "Implementación de un cliente BitTorrent con soporte para múltiples torrents simultáneos.",
    categoria: "Redes",
    tecnologias: ["Rust"],
    frameworks: ["Tokio"],
    basesdedatos: ["SQLite"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },

  // Go - 8 proyectos
  {
    titulo: "Microservicio de Autenticación",
    descripcion: "Servicio de autenticación y autorización con soporte para múltiples proveedores de identidad.",
    categoria: "Web",
    tecnologias: ["Go"],
    frameworks: ["Gin", "JWT"],
    basesdedatos: ["Redis", "PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Monitoreo de Contenedores",
    descripcion: "Herramienta para monitorear y gestionar contenedores Docker con métricas en tiempo real.",
    categoria: "DevOps",
    tecnologias: ["Go"],
    frameworks: ["Prometheus"],
    basesdedatos: ["InfluxDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "API Gateway",
    descripcion: "Puerta de enlace para gestionar y enrutar solicitudes a múltiples microservicios.",
    categoria: "Microservicios",
    tecnologias: ["Go"],
    frameworks: ["Echo"],
    basesdedatos: ["Redis"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "CLI para Cloud Provider",
    descripcion: "Herramienta de línea de comandos para interactuar con servicios de un proveedor de nube.",
    categoria: "Cloud",
    tecnologias: ["Go"],
    frameworks: ["Cobra"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Servidor de Chat en Tiempo Real",
    descripcion: "Servidor de chat con soporte para salas y mensajes privados usando WebSockets.",
    categoria: "Comunicación",
    tecnologias: ["Go"],
    frameworks: ["Gorilla WebSocket"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Archivos Distribuido",
    descripcion: "Implementación de un sistema de archivos distribuido con replicación y tolerancia a fallos.",
    categoria: "Sistemas",
    tecnologias: ["Go"],
    frameworks: ["gRPC"],
    basesdedatos: ["etcd"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Crawler Web",
    descripcion: "Rastreador web concurrente para indexar sitios y extraer información estructurada.",
    categoria: "Web",
    tecnologias: ["Go"],
    frameworks: ["Colly"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Consola Simple",
    descripcion: "Juego de texto interactivo para terminal con persistencia de estado.",
    categoria: "Juego",
    tecnologias: ["Go"],
    frameworks: ["tcell"],
    basesdedatos: ["BoltDB"],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },

  // Swift - 8 proyectos
  {
    titulo: "Aplicación de Notas con iCloud",
    descripcion: "App para tomar notas con sincronización vía iCloud y soporte para Markdown.",
    categoria: "Productividad",
    tecnologias: ["Swift"],
    frameworks: ["SwiftUI", "CloudKit"],
    basesdedatos: ["Core Data"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Rastreador de Hábitos",
    descripcion: "Aplicación para seguir hábitos diarios con estadísticas y recordatorios.",
    categoria: "Salud",
    tecnologias: ["Swift"],
    frameworks: ["SwiftUI", "Combine"],
    basesdedatos: ["Core Data"],
    nivel: "Trainee",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Reproductor de Podcasts",
    descripcion: "App para descubrir, descargar y reproducir podcasts con soporte para listas de reproducción.",
    categoria: "Multimedia",
    tecnologias: ["Swift"],
    frameworks: ["AVFoundation", "UIKit"],
    basesdedatos: ["Core Data"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Aplicación de Realidad Aumentada",
    descripcion: "Experiencia de RA que permite colocar objetos virtuales en el mundo real.",
    categoria: "AR/VR",
    tecnologias: ["Swift"],
    frameworks: ["ARKit", "SceneKit"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Cliente de Mensajería Segura",
    descripcion: "App de mensajería con cifrado de extremo a extremo y mensajes que se autodestruyen.",
    categoria: "Comunicación",
    tecnologias: ["Swift"],
    frameworks: ["SwiftUI", "CryptoKit"],
    basesdedatos: ["Core Data"],
    nivel: "Senior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Juego de Rompecabezas 2D",
    descripcion: "Juego de puzles con niveles progresivos y sistema de puntuación.",
    categoria: "Juego",
    tecnologias: ["Swift"],
    frameworks: ["SpriteKit"],
    basesdedatos: ["UserDefaults"],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Aplicación de Finanzas Personales",
    descripcion: "Herramienta para seguimiento de gastos con categorías, presupuestos y gráficos.",
    categoria: "Finanzas",
    tecnologias: ["Swift"],
    frameworks: ["SwiftUI", "Charts"],
    basesdedatos: ["Core Data"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Lector de Códigos QR y Barras",
    descripcion: "Aplicación para escanear y generar códigos QR y códigos de barras con historial.",
    categoria: "Utilidad",
    tecnologias: ["Swift"],
    frameworks: ["AVFoundation", "UIKit"],
    basesdedatos: ["Core Data"],
    nivel: "Trainee",
    tipo: "Aplicación Móvil",
  },

  // Kotlin - 8 proyectos
  {
    titulo: "Aplicación de Recetas de Cocina",
    descripcion: "App para descubrir, guardar y compartir recetas con búsqueda por ingredientes.",
    categoria: "Alimentación",
    tecnologias: ["Kotlin"],
    frameworks: ["Android Jetpack", "Retrofit"],
    basesdedatos: ["Room"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Rastreador de Ejercicios",
    descripcion: "Aplicación para registrar entrenamientos con GPS, estadísticas y progreso.",
    categoria: "Salud",
    tecnologias: ["Kotlin"],
    frameworks: ["Android Jetpack", "Google Maps API"],
    basesdedatos: ["Room"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Cliente de Reddit",
    descripcion: "Aplicación para navegar Reddit con soporte para múltiples cuentas y modo offline.",
    categoria: "Social",
    tecnologias: ["Kotlin"],
    frameworks: ["Android Jetpack", "Retrofit"],
    basesdedatos: ["Room"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Servicio Backend con Ktor",
    descripcion: "API RESTful con autenticación, autorización y documentación automática.",
    categoria: "Web",
    tecnologias: ["Kotlin"],
    frameworks: ["Ktor", "Exposed"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Notas con Markdown",
    descripcion: "Editor de notas con soporte para Markdown, etiquetas y sincronización en la nube.",
    categoria: "Productividad",
    tecnologias: ["Kotlin"],
    frameworks: ["Android Jetpack", "Compose"],
    basesdedatos: ["Room", "Firebase"],
    nivel: "Trainee",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Juego de Plataformas 2D",
    descripcion: "Videojuego de plataformas con niveles, enemigos y sistema de puntuación.",
    categoria: "Juego",
    tecnologias: ["Kotlin"],
    frameworks: ["LibGDX"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Aplicación de Transporte Público",
    descripcion: "App para consultar horarios, rutas y planificar viajes en transporte público.",
    categoria: "Transporte",
    tecnologias: ["Kotlin"],
    frameworks: ["Android Jetpack", "Google Maps API"],
    basesdedatos: ["Room"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Sistema de Automatización para Smart Home",
    descripcion: "Aplicación para controlar dispositivos IoT en el hogar con rutinas y escenas.",
    categoria: "IoT",
    tecnologias: ["Kotlin"],
    frameworks: ["Android Jetpack", "MQTT"],
    basesdedatos: ["Room", "Firebase"],
    nivel: "Senior",
    tipo: "Aplicación Móvil",
  },

  // Dart - 8 proyectos
  {
    titulo: "Aplicación de Gestión de Tareas",
    descripcion: "App multiplataforma para gestionar tareas con categorías, fechas límite y notificaciones.",
    categoria: "Productividad",
    tecnologias: ["Dart"],
    frameworks: ["Flutter"],
    basesdedatos: ["SQLite", "Firebase"],
    nivel: "Trainee",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Cliente de Chat en Tiempo Real",
    descripcion: "Aplicación de mensajería con chats grupales, mensajes privados y envío de archivos.",
    categoria: "Comunicación",
    tecnologias: ["Dart"],
    frameworks: ["Flutter", "Firebase"],
    basesdedatos: ["Firestore"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Aplicación de Comercio Electrónico",
    descripcion: "Tienda online completa con catálogo, carrito de compras y procesamiento de pagos.",
    categoria: "E-commerce",
    tecnologias: ["Dart"],
    frameworks: ["Flutter", "Provider"],
    basesdedatos: ["Firebase"],
    nivel: "Senior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Reproductor de Música",
    descripcion: "App para reproducir música local y en streaming con listas de reproducción y ecualizador.",
    categoria: "Multimedia",
    tecnologias: ["Dart"],
    frameworks: ["Flutter", "Just Audio"],
    basesdedatos: ["Hive"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Aplicación de Noticias",
    descripcion: "Lector de noticias con múltiples fuentes, categorías y modo offline.",
    categoria: "Noticias",
    tecnologias: ["Dart"],
    frameworks: ["Flutter", "Dio"],
    basesdedatos: ["Hive"],
    nivel: "Trainee",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Juego de Preguntas y Respuestas",
    descripcion: "Quiz con diferentes categorías, niveles de dificultad y tabla de clasificación.",
    categoria: "Juego",
    tecnologias: ["Dart"],
    frameworks: ["Flutter", "Flame"],
    basesdedatos: ["Hive", "Firebase"],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Dashboard de Análisis de Datos",
    descripcion: "Aplicación para visualizar y analizar datos con gráficos interactivos y filtros.",
    categoria: "Análisis de Datos",
    tecnologias: ["Dart"],
    frameworks: ["Flutter", "FL Chart"],
    basesdedatos: ["Firebase"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Aplicación de Realidad Aumentada",
    descripcion: "Experiencia de RA para visualizar modelos 3D en el mundo real.",
    categoria: "AR/VR",
    tecnologias: ["Dart"],
    frameworks: ["Flutter", "ARCore", "ARKit"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación Móvil",
  },

  // Ruby - 8 proyectos
  {
    titulo: "Blog con Ruby on Rails",
    descripcion: "Plataforma de blog completa con artículos, comentarios y panel de administración.",
    categoria: "Web",
    tecnologias: ["Ruby"],
    frameworks: ["Ruby on Rails"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "API RESTful para E-commerce",
    descripcion: "Backend para tienda online con productos, usuarios, pedidos y pagos.",
    categoria: "E-commerce",
    tecnologias: ["Ruby"],
    frameworks: ["Ruby on Rails", "Grape"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Contenido",
    descripcion: "CMS personalizado con editor WYSIWYG, gestión de usuarios y SEO.",
    categoria: "Web",
    tecnologias: ["Ruby"],
    frameworks: ["Ruby on Rails"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Herramienta de Automatización DevOps",
    descripcion: "Scripts para automatizar despliegues, pruebas y monitoreo de aplicaciones.",
    categoria: "DevOps",
    tecnologias: ["Ruby"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Plataforma de Cursos Online",
    descripcion: "Sistema para crear y consumir cursos con videos, cuestionarios y certificados.",
    categoria: "Educación",
    tecnologias: ["Ruby"],
    frameworks: ["Ruby on Rails", "Stimulus"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Generador de Informes PDF",
    descripcion: "Herramienta para crear informes en PDF a partir de datos estructurados.",
    categoria: "Utilidad",
    tecnologias: ["Ruby"],
    frameworks: ["Prawn"],
    basesdedatos: ["SQLite"],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Chatbot para Atención al Cliente",
    descripcion: "Bot conversacional para responder preguntas frecuentes y derivar a agentes humanos.",
    categoria: "IA",
    tecnologias: ["Ruby"],
    frameworks: ["Sinatra", "Rasa"],
    basesdedatos: ["Redis"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Aventura de Texto",
    descripcion: "Juego interactivo basado en texto con historia ramificada y sistema de inventario.",
    categoria: "Juego",
    tecnologias: ["Ruby"],
    frameworks: ["Gosu"],
    basesdedatos: ["YAML"],
    nivel: "Student",
    tipo: "Videojuego",
  },

  // PHP - 8 proyectos
  {
    titulo: "Sistema de Gestión de Contenido",
    descripcion: "CMS personalizado con editor de contenido, gestión de usuarios y temas.",
    categoria: "Web",
    tecnologias: ["PHP"],
    frameworks: ["Laravel"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Foro de Discusión",
    descripcion: "Plataforma de foros con categorías, hilos, respuestas y sistema de moderación.",
    categoria: "Comunidad",
    tecnologias: ["PHP"],
    frameworks: ["Symfony"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Reservas para Hoteles",
    descripcion: "Plataforma para gestionar reservas, habitaciones, clientes y pagos en hoteles.",
    categoria: "Turismo",
    tecnologias: ["PHP"],
    frameworks: ["Laravel"],
    basesdedatos: ["MySQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "API RESTful con OAuth",
    descripcion: "Servicio web con autenticación OAuth2 y documentación automática.",
    categoria: "Web",
    tecnologias: ["PHP"],
    frameworks: ["Slim", "Doctrine"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión Escolar",
    descripcion: "Plataforma para administrar estudiantes, profesores, cursos, calificaciones y asistencia.",
    categoria: "Educación",
    tecnologias: ["PHP"],
    frameworks: ["Laravel"],
    basesdedatos: ["MySQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Tienda Online con WooCommerce",
    descripcion: "E-commerce personalizado con catálogo, carrito, pagos y gestión de inventario.",
    categoria: "E-commerce",
    tecnologias: ["PHP"],
    frameworks: ["WordPress", "WooCommerce"],
    basesdedatos: ["MySQL"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Tickets de Soporte",
    descripcion: "Plataforma para gestionar tickets de soporte con prioridades, categorías y seguimiento.",
    categoria: "Soporte",
    tecnologias: ["PHP"],
    frameworks: ["Laravel"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Quiz Interactivo",
    descripcion: "Aplicación de preguntas y respuestas con diferentes categorías y niveles de dificultad.",
    categoria: "Educación",
    tecnologias: ["PHP"],
    frameworks: ["CodeIgniter"],
    basesdedatos: ["MySQL"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },

  // Brainfuck (Easter Egg) - 4 proyectos
  {
    titulo: "Generador de 'Hola Mundo'",
    descripcion: "Programa que genera la frase 'Hola Mundo' en la consola.",
    categoria: "Esotérico",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora Simple",
    descripcion: "Implementación de una calculadora básica que puede sumar números de un solo dígito.",
    categoria: "Esotérico",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Generador de Secuencia de Fibonacci",
    descripcion: "Programa que genera los primeros números de la secuencia de Fibonacci.",
    categoria: "Esotérico",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Intérprete de Brainfuck",
    descripcion: "Un intérprete de Brainfuck escrito en Brainfuck (meta-intérprete).",
    categoria: "Esotérico",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },

  // Crystal - 6 proyectos
  {
    titulo: "API RESTful con Kemal",
    descripcion: "Servicio web rápido y eficiente con autenticación y documentación.",
    categoria: "Web",
    tecnologias: ["Crystal"],
    frameworks: ["Kemal"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "CLI para Gestión de Proyectos",
    descripcion: "Herramienta de línea de comandos para gestionar tareas y proyectos localmente.",
    categoria: "Productividad",
    tecnologias: ["Crystal"],
    frameworks: [],
    basesdedatos: ["SQLite"],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Servidor de Chat en Tiempo Real",
    descripcion: "Servidor de chat con WebSockets para comunicación en tiempo real.",
    categoria: "Comunicación",
    tecnologias: ["Crystal"],
    frameworks: ["Kemal"],
    basesdedatos: ["Redis"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Microservicio de Procesamiento de Imágenes",
    descripcion: "Servicio para procesar y transformar imágenes con alto rendimiento.",
    categoria: "Multimedia",
    tecnologias: ["Crystal"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Monitoreo de Recursos",
    descripcion: "Herramienta para monitorear recursos del sistema con métricas y alertas.",
    categoria: "DevOps",
    tecnologias: ["Crystal"],
    frameworks: [],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Consola Simple",
    descripcion: "Juego de texto interactivo para terminal con comandos simples.",
    categoria: "Juego",
    tecnologias: ["Crystal"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },

  // Nim - 6 proyectos
  {
    titulo: "Servidor Web de Alto Rendimiento",
    descripcion: "Implementación de un servidor web ligero y rápido con manejo asíncrono.",
    categoria: "Web",
    tecnologias: ["Nim"],
    frameworks: ["Jester"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Herramienta de Análisis de Datos",
    descripcion: "Aplicación para procesar y analizar conjuntos de datos con generación de informes.",
    categoria: "Análisis de Datos",
    tecnologias: ["Nim"],
    frameworks: [],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Compilador para DSL",
    descripcion: "Compilador para un lenguaje específico de dominio simple.",
    categoria: "Desarrollo",
    tecnologias: ["Nim"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego 2D con SDL",
    descripcion: "Videojuego 2D simple con gráficos, sonido y sistema de puntuación.",
    categoria: "Juego",
    tecnologias: ["Nim"],
    frameworks: ["SDL2"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "CLI para Gestión de Notas",
    descripcion: "Herramienta de línea de comandos para tomar y organizar notas con etiquetas.",
    categoria: "Productividad",
    tecnologias: ["Nim"],
    frameworks: [],
    basesdedatos: ["SQLite"],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Automatización de Tareas",
    descripcion: "Herramienta para automatizar tareas repetitivas del sistema con programación.",
    categoria: "Utilidad",
    tecnologias: ["Nim"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },

  // Zig - 6 proyectos
  {
    titulo: "Biblioteca de Estructuras de Datos",
    descripcion: "Implementación eficiente de estructuras de datos comunes con enfoque en rendimiento.",
    categoria: "Desarrollo",
    tecnologias: ["Zig"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Emulador de Chip-8",
    descripcion: "Implementación de un emulador para el sistema Chip-8 con enfoque en precisión.",
    categoria: "Sistemas",
    tecnologias: ["Zig"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Servidor HTTP Minimalista",
    descripcion: "Servidor web ligero y de alto rendimiento con manejo eficiente de memoria.",
    categoria: "Web",
    tecnologias: ["Zig"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Compresión de Datos",
    descripcion: "Implementación de algoritmos de compresión con optimización de rendimiento.",
    categoria: "Utilidad",
    tecnologias: ["Zig"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Consola Simple",
    descripcion: "Juego de texto interactivo para terminal con manejo eficiente de recursos.",
    categoria: "Juego",
    tecnologias: ["Zig"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Intérprete para Lenguaje Simple",
    descripcion: "Intérprete para un lenguaje de programación minimalista con enfoque educativo.",
    categoria: "Desarrollo",
    tecnologias: ["Zig"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },

  // OCaml - 6 proyectos
  {
    titulo: "Verificador de Tipos Estático",
    descripcion: "Herramienta para verificar tipos en código fuente de forma estática.",
    categoria: "Desarrollo",
    tecnologias: ["OCaml"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Compilador para Lenguaje Funcional",
    descripcion: "Implementación de un compilador para un lenguaje funcional simple.",
    categoria: "Desarrollo",
    tecnologias: ["OCaml"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Servidor Web Funcional",
    descripcion: "Implementación de un servidor web con programación funcional pura.",
    categoria: "Web",
    tecnologias: ["OCaml"],
    frameworks: ["Dream"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Inferencia de Tipos",
    descripcion: "Implementación del algoritmo Hindley-Milner para inferencia de tipos.",
    categoria: "Desarrollo",
    tecnologias: ["OCaml"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Asistente de Pruebas Formales",
    descripcion: "Herramienta para ayudar en la creación y verificación de pruebas formales.",
    categoria: "Desarrollo",
    tecnologias: ["OCaml"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Estrategia por Turnos",
    descripcion: "Juego de estrategia simple con IA básica implementada funcionalmente.",
    categoria: "Juego",
    tecnologias: ["OCaml"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },

  // Erlang - 6 proyectos
  {
    titulo: "Sistema de Chat Distribuido",
    descripcion: "Plataforma de chat escalable con tolerancia a fallos y distribución.",
    categoria: "Comunicación",
    tecnologias: ["Erlang"],
    frameworks: ["OTP"],
    basesdedatos: ["Mnesia"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Monitoreo Distribuido",
    descripcion: "Herramienta para monitorear sistemas distribuidos con alertas y métricas.",
    categoria: "DevOps",
    tecnologias: ["Erlang"],
    frameworks: ["OTP"],
    basesdedatos: ["Mnesia"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Servidor de Juegos Multijugador",
    descripcion: "Backend para juegos multijugador en tiempo real con alta concurrencia.",
    categoria: "Juego",
    tecnologias: ["Erlang"],
    frameworks: ["OTP"],
    basesdedatos: ["Mnesia"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Colas Distribuido",
    descripcion: "Implementación de un sistema de colas de mensajes distribuido y tolerante a fallos.",
    categoria: "Infraestructura",
    tecnologias: ["Erlang"],
    frameworks: ["OTP"],
    basesdedatos: ["Mnesia"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Servidor XMPP",
    descripcion: "Implementación de un servidor de mensajería XMPP con extensiones personalizadas.",
    categoria: "Comunicación",
    tecnologias: ["Erlang"],
    frameworks: ["OTP"],
    basesdedatos: ["Mnesia"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Simulador de Sistemas Concurrentes",
    descripcion: "Herramienta para simular y analizar sistemas concurrentes con visualización.",
    categoria: "Educación",
    tecnologias: ["Erlang"],
    frameworks: ["OTP"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },

  // Racket - 6 proyectos
  {
    titulo: "Intérprete de Lenguaje Educativo",
    descripcion: "Implementación de un lenguaje de programación para enseñanza con depurador visual.",
    categoria: "Educación",
    tecnologias: ["Racket"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Generador de Documentación",
    descripcion: "Herramienta para generar documentación a partir de código fuente con análisis estático.",
    categoria: "Desarrollo",
    tecnologias: ["Racket"],
    frameworks: ["Scribble"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Entorno de Desarrollo Simple",
    descripcion: "IDE minimalista para programación con resaltado de sintaxis y evaluación interactiva.",
    categoria: "Desarrollo",
    tecnologias: ["Racket"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Puzles Lógicos",
    descripcion: "Colección de puzles lógicos con generación procedural y soluciones.",
    categoria: "Juego",
    tecnologias: ["Racket"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Visualizador de Estructuras de Datos",
    descripcion: "Herramienta educativa para visualizar estructuras de datos y algoritmos.",
    categoria: "Educación",
    tecnologias: ["Racket"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Servidor Web Minimalista",
    descripcion: "Implementación de un servidor web simple con manejo de rutas y plantillas.",
    categoria: "Web",
    tecnologias: ["Racket"],
    frameworks: ["Web Server"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
]
