// Definir tipos
import type { ProjectIdea } from "./project-ideas"

// Lista adicional de ideas con más lenguajes de programación
export const additionalProjectIdeas: ProjectIdea[] = [
  // R - 10 proyectos
  {
    titulo: "Dashboard de Análisis Estadístico",
    descripcion: "Aplicación web interactiva para análisis estadístico con visualizaciones personalizables.",
    categoria: "Análisis de Datos",
    tecnologias: ["R"],
    frameworks: ["Shiny"],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Modelo Predictivo para Ventas",
    descripcion: "Sistema que predice ventas futuras basado en datos históricos y variables externas.",
    categoria: "Análisis de Datos",
    tecnologias: ["R"],
    frameworks: ["Tidyverse"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Herramienta de Análisis de Sentimientos",
    descripcion: "Aplicación que analiza el sentimiento de textos y comentarios con visualización de resultados.",
    categoria: "Análisis de Datos",
    tecnologias: ["R"],
    frameworks: ["Shiny", "Tidytext"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Recomendación de Productos",
    descripcion: "Motor de recomendación basado en comportamiento de usuarios y similitud de productos.",
    categoria: "IA",
    tecnologias: ["R"],
    frameworks: ["Recommenderlab"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Visualizador de Datos Geoespaciales",
    descripcion: "Aplicación para visualizar y analizar datos geoespaciales con mapas interactivos.",
    categoria: "Visualización",
    tecnologias: ["R"],
    frameworks: ["Leaflet", "Shiny"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Herramienta de Análisis de Series Temporales",
    descripcion: "Aplicación para analizar y predecir series temporales con diferentes modelos estadísticos.",
    categoria: "Análisis de Datos",
    tecnologias: ["R"],
    frameworks: ["Forecast", "Shiny"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Dashboard para Análisis de Redes Sociales",
    descripcion: "Herramienta para analizar datos de redes sociales con métricas y visualizaciones.",
    categoria: "Análisis de Datos",
    tecnologias: ["R"],
    frameworks: ["Shiny", "Igraph"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Clustering de Clientes",
    descripcion: "Sistema que segmenta clientes basado en comportamiento y características.",
    categoria: "IA",
    tecnologias: ["R"],
    frameworks: ["Tidyverse", "Cluster"],
    basesdedatos: ["MySQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Herramienta de Análisis de Texto",
    descripcion: "Aplicación para analizar textos, extraer temas y visualizar resultados.",
    categoria: "Análisis de Datos",
    tecnologias: ["R"],
    frameworks: ["Tidytext", "Shiny"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Dashboard de Análisis Financiero",
    descripcion: "Aplicación para análisis y visualización de datos financieros con indicadores clave.",
    categoria: "Finanzas",
    tecnologias: ["R"],
    frameworks: ["Shiny", "Quantmod"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // COBOL - 5 proyectos
  {
    titulo: "Sistema de Nómina Empresarial",
    descripcion: "Aplicación para gestionar el cálculo y procesamiento de nóminas para empresas.",
    categoria: "Finanzas",
    tecnologias: ["COBOL"],
    frameworks: [],
    basesdedatos: ["DB2"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Contabilidad Bancaria",
    descripcion: "Aplicación para gestionar transacciones bancarias y contabilidad interna.",
    categoria: "Finanzas",
    tecnologias: ["COBOL"],
    frameworks: [],
    basesdedatos: ["VSAM"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Procesador de Transacciones Financieras",
    descripcion: "Sistema para procesar grandes volúmenes de transacciones financieras en lotes.",
    categoria: "Finanzas",
    tecnologias: ["COBOL"],
    frameworks: [],
    basesdedatos: ["DB2"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Gestión de Seguros",
    descripcion: "Aplicación para gestionar pólizas, reclamaciones y clientes de seguros.",
    categoria: "Seguros",
    tecnologias: ["COBOL"],
    frameworks: [],
    basesdedatos: ["VSAM"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Inventario y Facturación",
    descripcion: "Aplicación para gestionar inventario, ventas y facturación para empresas.",
    categoria: "Negocios",
    tecnologias: ["COBOL"],
    frameworks: [],
    basesdedatos: ["VSAM"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },

  // Scala - 10 proyectos
  {
    titulo: "Plataforma de Procesamiento de Datos en Tiempo Real",
    descripcion: "Sistema para procesar y analizar grandes volúmenes de datos en tiempo real.",
    categoria: "Big Data",
    tecnologias: ["Scala"],
    frameworks: ["Akka", "Spark"],
    basesdedatos: ["Cassandra"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Motor de Recomendaciones Escalable",
    descripcion: "Sistema de recomendación de alta escalabilidad para aplicaciones de comercio electrónico.",
    categoria: "IA",
    tecnologias: ["Scala"],
    frameworks: ["Spark", "Play"],
    basesdedatos: ["Cassandra"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "API RESTful con Autenticación",
    descripcion: "Servicio web RESTful con autenticación OAuth y JWT para aplicaciones móviles.",
    categoria: "Web",
    tecnologias: ["Scala"],
    frameworks: ["Play"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Procesamiento de Eventos",
    descripcion: "Plataforma para procesar y reaccionar a eventos en tiempo real con arquitectura orientada a eventos.",
    categoria: "Infraestructura",
    tecnologias: ["Scala"],
    frameworks: ["Akka"],
    basesdedatos: ["Kafka"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación Web Reactiva",
    descripcion: "Aplicación web con interfaces reactivas y comunicación en tiempo real.",
    categoria: "Web",
    tecnologias: ["Scala"],
    frameworks: ["Play", "Akka"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Análisis de Datos",
    descripcion: "Sistema para analizar grandes conjuntos de datos con procesamiento distribuido.",
    categoria: "Big Data",
    tecnologias: ["Scala"],
    frameworks: ["Spark"],
    basesdedatos: ["HDFS"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Microservicio de Gestión de Usuarios",
    descripcion: "Servicio para gestionar usuarios, autenticación y autorización en arquitecturas de microservicios.",
    categoria: "Microservicios",
    tecnologias: ["Scala"],
    frameworks: ["Akka HTTP"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Trading Algorítmico",
    descripcion: "Plataforma para ejecutar estrategias de trading automatizadas con baja latencia.",
    categoria: "Finanzas",
    tecnologias: ["Scala"],
    frameworks: ["Akka"],
    basesdedatos: ["InfluxDB"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de ETL Distribuida",
    descripcion: "Sistema para extraer, transformar y cargar datos a gran escala de forma distribuida.",
    categoria: "Big Data",
    tecnologias: ["Scala"],
    frameworks: ["Spark"],
    basesdedatos: ["HDFS", "PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Chatbot con Procesamiento de Lenguaje Natural",
    descripcion: "Bot conversacional que utiliza NLP para entender y responder consultas de usuarios.",
    categoria: "IA",
    tecnologias: ["Scala"],
    frameworks: ["Play", "Akka"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Haskell - 5 proyectos
  {
    titulo: "Compilador para Lenguaje Personalizado",
    descripcion: "Implementación de un compilador para un lenguaje de programación específico.",
    categoria: "Desarrollo",
    tecnologias: ["Haskell"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Verificador de Tipos Estático",
    descripcion: "Herramienta para verificar tipos en código fuente de forma estática.",
    categoria: "Desarrollo",
    tecnologias: ["Haskell"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "API Web Funcional",
    descripcion: "Servicio web implementado con programación funcional pura.",
    categoria: "Web",
    tecnologias: ["Haskell"],
    frameworks: ["Servant"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Análisis Formal",
    descripcion: "Herramienta para análisis formal y verificación de programas.",
    categoria: "Desarrollo",
    tecnologias: ["Haskell"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Procesador de Lenguaje Natural",
    descripcion: "Sistema para analizar y procesar texto en lenguaje natural con enfoque funcional.",
    categoria: "IA",
    tecnologias: ["Haskell"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },

  // Perl - 5 proyectos
  {
    titulo: "Sistema de Procesamiento de Logs",
    descripcion: "Herramienta para analizar y procesar archivos de registro con expresiones regulares.",
    categoria: "DevOps",
    tecnologias: ["Perl"],
    frameworks: [],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Automatización de Tareas de Administración",
    descripcion: "Scripts para automatizar tareas comunes de administración de sistemas.",
    categoria: "DevOps",
    tecnologias: ["Perl"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Extracción de Datos Web",
    descripcion: "Sistema para extraer datos de sitios web y convertirlos a formatos estructurados.",
    categoria: "Web",
    tecnologias: ["Perl"],
    frameworks: [],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Monitoreo de Red",
    descripcion: "Aplicación para monitorear dispositivos de red y generar alertas.",
    categoria: "Redes",
    tecnologias: ["Perl"],
    frameworks: [],
    basesdedatos: ["RRD"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Procesador de Archivos de Texto",
    descripcion: "Herramienta para procesar y transformar archivos de texto con patrones complejos.",
    categoria: "Utilidad",
    tecnologias: ["Perl"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },

  // Lua - 5 proyectos
  {
    titulo: "Motor de Juego 2D",
    descripcion: "Motor para crear juegos 2D con física y animaciones.",
    categoria: "Juego",
    tecnologias: ["Lua"],
    frameworks: ["LÖVE"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Scripting para Aplicaciones",
    descripcion: "Sistema para añadir capacidades de scripting a aplicaciones existentes.",
    categoria: "Desarrollo",
    tecnologias: ["Lua"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Plataformas",
    descripcion: "Juego de plataformas con niveles, enemigos y coleccionables.",
    categoria: "Juego",
    tecnologias: ["Lua"],
    frameworks: ["LÖVE"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Automatización para Servidores",
    descripcion: "Scripts para automatizar tareas en servidores web.",
    categoria: "DevOps",
    tecnologias: ["Lua"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Editor de Texto Extensible",
    descripcion: "Editor de texto con sistema de plugins y personalización.",
    categoria: "Utilidad",
    tecnologias: ["Lua"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },

  // Elixir - 10 proyectos
  {
    titulo: "Sistema de Chat en Tiempo Real",
    descripcion: "Plataforma de chat escalable con salas y mensajes privados.",
    categoria: "Comunicación",
    tecnologias: ["Elixir"],
    frameworks: ["Phoenix"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "API de Alta Concurrencia",
    descripcion: "Servicio web diseñado para manejar miles de conexiones simultáneas.",
    categoria: "Web",
    tecnologias: ["Elixir"],
    frameworks: ["Phoenix"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Procesamiento Distribuido",
    descripcion: "Plataforma para procesar tareas de forma distribuida con tolerancia a fallos.",
    categoria: "Infraestructura",
    tecnologias: ["Elixir"],
    frameworks: ["OTP"],
    basesdedatos: ["Redis"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de IoT",
    descripcion: "Sistema para conectar, monitorear y controlar dispositivos IoT.",
    categoria: "IoT",
    tecnologias: ["Elixir"],
    frameworks: ["Nerves"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Notificaciones en Tiempo Real",
    descripcion: "Servicio para enviar notificaciones a usuarios a través de múltiples canales.",
    categoria: "Comunicación",
    tecnologias: ["Elixir"],
    frameworks: ["Phoenix"],
    basesdedatos: ["Redis"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Streaming de Video",
    descripcion: "Sistema para transmitir video en tiempo real a múltiples usuarios.",
    categoria: "Multimedia",
    tecnologias: ["Elixir"],
    frameworks: ["Phoenix"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Monitoreo Distribuido",
    descripcion: "Plataforma para monitorear servicios distribuidos con alertas y métricas.",
    categoria: "DevOps",
    tecnologias: ["Elixir"],
    frameworks: ["OTP"],
    basesdedatos: ["InfluxDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "API Gateway para Microservicios",
    descripcion: "Puerta de enlace para enrutar y gestionar solicitudes a microservicios.",
    categoria: "Microservicios",
    tecnologias: ["Elixir"],
    frameworks: ["Phoenix"],
    basesdedatos: ["Redis"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Juegos Multijugador",
    descripcion: "Sistema para crear y gestionar juegos multijugador en tiempo real.",
    categoria: "Juego",
    tecnologias: ["Elixir"],
    frameworks: ["Phoenix"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Colas Distribuido",
    descripcion: "Implementación de un sistema de colas de mensajes distribuido y tolerante a fallos.",
    categoria: "Infraestructura",
    tecnologias: ["Elixir"],
    frameworks: ["OTP"],
    basesdedatos: ["Redis"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Clojure - 5 proyectos
  {
    titulo: "Aplicación Web Reactiva",
    descripcion: "Aplicación web con interfaces reactivas utilizando programación funcional.",
    categoria: "Web",
    tecnologias: ["Clojure"],
    frameworks: ["Reagent"],
    basesdedatos: ["Datomic"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Análisis de Datos",
    descripcion: "Plataforma para analizar y visualizar datos con enfoque funcional.",
    categoria: "Análisis de Datos",
    tecnologias: ["Clojure"],
    frameworks: ["Incanter"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "API RESTful Funcional",
    descripcion: "Servicio web implementado con programación funcional y datos inmutables.",
    categoria: "Web",
    tecnologias: ["Clojure"],
    frameworks: ["Ring", "Compojure"],
    basesdedatos: ["Datomic"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Procesamiento de Eventos",
    descripcion: "Plataforma para procesar flujos de eventos con transformaciones funcionales.",
    categoria: "Infraestructura",
    tecnologias: ["Clojure"],
    frameworks: ["Core.async"],
    basesdedatos: ["Kafka"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Herramienta de Generación de Informes",
    descripcion: "Sistema para generar informes complejos a partir de múltiples fuentes de datos.",
    categoria: "Empresarial",
    tecnologias: ["Clojure"],
    frameworks: ["Hiccup"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },

  // F# - 5 proyectos
  {
    titulo: "Aplicación Financiera",
    descripcion: "Sistema para análisis y modelado financiero con programación funcional.",
    categoria: "Finanzas",
    tecnologias: ["F#"],
    frameworks: [".NET Core"],
    basesdedatos: ["SQL Server"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "API Web con CQRS",
    descripcion: "Servicio web implementado con patrón CQRS y programación funcional.",
    categoria: "Web",
    tecnologias: ["F#"],
    frameworks: ["Giraffe", "ASP.NET Core"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Procesamiento de Datos Científicos",
    descripcion: "Plataforma para procesar y analizar datos científicos con enfoque funcional.",
    categoria: "Ciencia",
    tecnologias: ["F#"],
    frameworks: ["Deedle"],
    basesdedatos: ["SQLite"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Verificación Formal",
    descripcion: "Sistema para verificar formalmente propiedades de programas.",
    categoria: "Desarrollo",
    tecnologias: ["F#"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Aplicación de Procesamiento de Imágenes",
    descripcion: "Herramienta para procesar y analizar imágenes con algoritmos funcionales.",
    categoria: "Multimedia",
    tecnologias: ["F#"],
    frameworks: [".NET Core"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },

  // Julia - 5 proyectos
  {
    titulo: "Sistema de Modelado Matemático",
    descripcion: "Plataforma para crear y resolver modelos matemáticos complejos.",
    categoria: "Ciencia",
    tecnologias: ["Julia"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Análisis Estadístico",
    descripcion: "Aplicación para realizar análisis estadísticos avanzados con alto rendimiento.",
    categoria: "Análisis de Datos",
    tecnologias: ["Julia"],
    frameworks: ["Genie.jl"],
    basesdedatos: ["SQLite"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Simulación Numérica",
    descripcion: "Plataforma para realizar simulaciones numéricas de sistemas físicos.",
    categoria: "Ciencia",
    tecnologias: ["Julia"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Optimización",
    descripcion: "Aplicación para resolver problemas de optimización complejos.",
    categoria: "Ciencia",
    tecnologias: ["Julia"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Dashboard de Visualización Científica",
    descripcion: "Aplicación web para visualizar datos científicos con gráficos interactivos.",
    categoria: "Visualización",
    tecnologias: ["Julia"],
    frameworks: ["Genie.jl"],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },

  // Groovy - 5 proyectos
  {
    titulo: "Sistema de Automatización de Pruebas",
    descripcion: "Plataforma para automatizar pruebas de software con scripts flexibles.",
    categoria: "Testing",
    tecnologias: ["Groovy"],
    frameworks: ["Spock"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Integración Continua",
    descripcion: "Sistema para automatizar la integración y despliegue de aplicaciones.",
    categoria: "DevOps",
    tecnologias: ["Groovy"],
    frameworks: ["Gradle"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "API RESTful con Grails",
    descripcion: "Servicio web implementado con framework Grails para desarrollo rápido.",
    categoria: "Web",
    tecnologias: ["Groovy"],
    frameworks: ["Grails"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Generación de Informes",
    descripcion: "Herramienta para generar informes dinámicos a partir de múltiples fuentes de datos.",
    categoria: "Empresarial",
    tecnologias: ["Groovy"],
    frameworks: ["Grails"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Herramienta de Procesamiento de DSL",
    descripcion: "Sistema para procesar lenguajes específicos de dominio y generar código.",
    categoria: "Desarrollo",
    tecnologias: ["Groovy"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },

  // Objective-C - 5 proyectos
  {
    titulo: "Aplicación de Productividad para iOS",
    descripcion: "App para gestionar tareas, notas y recordatorios con sincronización en la nube.",
    categoria: "Productividad",
    tecnologias: ["Objective-C"],
    frameworks: ["UIKit", "CoreData"],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Reproductor de Medios para macOS",
    descripcion: "Aplicación para reproducir audio y video con funciones avanzadas.",
    categoria: "Multimedia",
    tecnologias: ["Objective-C"],
    frameworks: ["AVFoundation", "AppKit"],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Aplicación de Edición de Fotos",
    descripcion: "Herramienta para editar y aplicar filtros a imágenes en dispositivos iOS.",
    categoria: "Multimedia",
    tecnologias: ["Objective-C"],
    frameworks: ["UIKit", "CoreImage"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Cliente de Email para macOS",
    descripcion: "Aplicación de correo electrónico con soporte para múltiples cuentas y protocolos.",
    categoria: "Comunicación",
    tecnologias: ["Objective-C"],
    frameworks: ["AppKit"],
    basesdedatos: ["CoreData"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Aplicación de Navegación GPS",
    descripcion: "App de navegación con mapas offline y direcciones paso a paso.",
    categoria: "Navegación",
    tecnologias: ["Objective-C"],
    frameworks: ["MapKit", "CoreLocation"],
    basesdedatos: ["SQLite"],
    nivel: "Senior",
    tipo: "Aplicación Móvil",
  },

  // Assembly - 5 proyectos
  {
    titulo: "Kernel Minimalista",
    descripcion: "Implementación de un kernel básico para sistemas embebidos.",
    categoria: "Sistemas",
    tecnologias: ["Assembly"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Optimizador de Rutinas Críticas",
    descripcion: "Biblioteca de funciones optimizadas para operaciones de alto rendimiento.",
    categoria: "Rendimiento",
    tecnologias: ["Assembly"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Emulador de Procesador",
    descripcion: "Emulador para una arquitectura de procesador específica.",
    categoria: "Sistemas",
    tecnologias: ["Assembly"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Driver para Dispositivo Hardware",
    descripcion: "Driver para controlar un dispositivo hardware específico a bajo nivel.",
    categoria: "Sistemas",
    tecnologias: ["Assembly"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Algoritmos Criptográficos Optimizados",
    descripcion: "Implementación optimizada de algoritmos criptográficos para máximo rendimiento.",
    categoria: "Seguridad",
    tecnologias: ["Assembly"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },

  // MATLAB - 5 proyectos
  {
    titulo: "Sistema de Procesamiento de Señales",
    descripcion: "Aplicación para analizar y procesar señales digitales con visualización avanzada.",
    categoria: "Procesamiento de Señales",
    tecnologias: ["MATLAB"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Simulador de Sistemas Dinámicos",
    descripcion: "Herramienta para modelar y simular sistemas dinámicos con ecuaciones diferenciales.",
    categoria: "Simulación",
    tecnologias: ["MATLAB"],
    frameworks: ["Simulink"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Procesador de Imágenes Médicas",
    descripcion: "Sistema para procesar y analizar imágenes médicas como resonancias y tomografías.",
    categoria: "Salud",
    tecnologias: ["MATLAB"],
    frameworks: ["Image Processing Toolbox"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Control Automático",
    descripcion: "Aplicación para diseñar y simular sistemas de control automático.",
    categoria: "Control",
    tecnologias: ["MATLAB"],
    frameworks: ["Control System Toolbox"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Análisis Estadístico",
    descripcion: "Aplicación para realizar análisis estadísticos avanzados con visualizaciones.",
    categoria: "Análisis de Datos",
    tecnologias: ["MATLAB"],
    frameworks: ["Statistics Toolbox"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },

  // VBA - 5 proyectos
  {
    titulo: "Sistema de Gestión de Inventario en Excel",
    descripcion: "Aplicación en Excel para gestionar inventario con formularios personalizados.",
    categoria: "Negocios",
    tecnologias: ["VBA"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Automatización de Informes Financieros",
    descripcion: "Sistema para generar informes financieros automáticamente a partir de datos en Excel.",
    categoria: "Finanzas",
    tecnologias: ["VBA"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Gestor de Proyectos en Excel",
    descripcion: "Aplicación para gestionar proyectos con diagramas de Gantt y seguimiento de tareas.",
    categoria: "Productividad",
    tecnologias: ["VBA"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Facturación en Excel",
    descripcion: "Aplicación para crear y gestionar facturas con base de datos de clientes y productos.",
    categoria: "Negocios",
    tecnologias: ["VBA"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Dashboard Interactivo en Excel",
    descripcion: "Panel de control con gráficos interactivos y filtros dinámicos para análisis de datos.",
    categoria: "Análisis de Datos",
    tecnologias: ["VBA"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },

  // Shell/Bash - 5 proyectos
  {
    titulo: "Sistema de Backup Automatizado",
    descripcion: "Scripts para realizar copias de seguridad automáticas de archivos y bases de datos.",
    categoria: "DevOps",
    tecnologias: ["Bash"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Monitoreo de Servidores",
    descripcion: "Sistema para monitorear el estado y rendimiento de servidores con alertas.",
    categoria: "DevOps",
    tecnologias: ["Bash"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Automatización de Despliegue",
    descripcion: "Scripts para automatizar el despliegue de aplicaciones en diferentes entornos.",
    categoria: "DevOps",
    tecnologias: ["Bash"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Gestor de Entornos de Desarrollo",
    descripcion: "Herramienta para configurar y gestionar entornos de desarrollo consistentes.",
    categoria: "DevOps",
    tecnologias: ["Bash"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Analizador de Logs",
    descripcion: "Sistema para analizar archivos de registro y generar informes de errores y actividad.",
    categoria: "DevOps",
    tecnologias: ["Bash"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },

  // PowerShell - 5 proyectos
  {
    titulo: "Gestor de Infraestructura Windows",
    descripcion: "Herramienta para administrar y monitorear servidores Windows en red.",
    categoria: "DevOps",
    tecnologias: ["PowerShell"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Automatización de Active Directory",
    descripcion: "Scripts para gestionar usuarios, grupos y políticas en Active Directory.",
    categoria: "Administración",
    tecnologias: ["PowerShell"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Gestor de Actualizaciones de Windows",
    descripcion: "Sistema para gestionar y aplicar actualizaciones en múltiples equipos Windows.",
    categoria: "Administración",
    tecnologias: ["PowerShell"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Auditoría de Seguridad",
    descripcion: "Sistema para auditar la seguridad de sistemas Windows y generar informes.",
    categoria: "Seguridad",
    tecnologias: ["PowerShell"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Dashboard de Monitoreo de Azure",
    descripcion: "Panel para monitorear y gestionar recursos en Microsoft Azure.",
    categoria: "Cloud",
    tecnologias: ["PowerShell"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },

  // SQL - 5 proyectos
  {
    titulo: "Sistema de Análisis de Datos de Ventas",
    descripcion: "Conjunto de consultas y procedimientos para analizar datos de ventas y generar informes.",
    categoria: "Análisis de Datos",
    tecnologias: ["SQL"],
    frameworks: [],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Datawarehouse para Business Intelligence",
    descripcion: "Implementación de un almacén de datos para análisis de negocio con ETL.",
    categoria: "Business Intelligence",
    tecnologias: ["SQL"],
    frameworks: [],
    basesdedatos: ["SQL Server"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Gestión de Inventario",
    descripcion: "Base de datos y procedimientos almacenados para gestionar inventario y ventas.",
    categoria: "Negocios",
    tecnologias: ["SQL"],
    frameworks: [],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Optimizador de Consultas",
    descripcion: "Herramienta para analizar y optimizar consultas SQL complejas.",
    categoria: "Rendimiento",
    tecnologias: ["SQL"],
    frameworks: [],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Reportes Automatizados",
    descripcion: "Conjunto de vistas y procedimientos para generar informes periódicos automáticamente.",
    categoria: "Análisis de Datos",
    tecnologias: ["SQL"],
    frameworks: [],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  // Proyectos para Brainfuck (Easter Egg)
  {
    titulo: "Contador Simple",
    descripcion: "Implementa un contador que incremente y muestre números del 0 al 9 en Brainfuck.",
    categoria: "Programación Esotérica",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Generador de ASCII Art",
    descripcion:
      "Crea un programa en Brainfuck que genere un patrón simple de ASCII art como una cara sonriente o un corazón.",
    categoria: "Arte Digital",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Calculadora Básica",
    descripcion: "Desarrolla una calculadora que pueda sumar dos números de un solo dígito en Brainfuck.",
    categoria: "Matemáticas",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Hello World Optimizado",
    descripcion: "Crea la versión más optimizada y corta posible de un programa 'Hello World' en Brainfuck.",
    categoria: "Optimización",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Conversor de Texto a Brainfuck",
    descripcion: "Desarrolla un programa que convierta texto simple en código Brainfuck que imprime ese texto.",
    categoria: "Compiladores",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Juego de Adivinanza",
    descripcion: "Implementa un juego simple donde el usuario debe adivinar un número generado aleatoriamente.",
    categoria: "Juegos",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Generador de Secuencia de Fibonacci",
    descripcion: "Crea un programa que genere y muestre los primeros números de la secuencia de Fibonacci.",
    categoria: "Matemáticas",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Intérprete de Brainfuck",
    descripcion: "Implementa un intérprete de Brainfuck en Brainfuck (meta-intérprete).",
    categoria: "Compiladores",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Verificador de Palíndromos",
    descripcion: "Desarrolla un programa que verifique si una palabra ingresada es un palíndromo.",
    categoria: "Algoritmos",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Reloj Digital Simple",
    descripcion: "Crea un reloj digital que muestre la hora actual en formato HH:MM.",
    categoria: "Utilidades",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Consola",
  },
]

// Proyectos de Brainfuck
export const brainfuckProjects = [
  {
    id: 1001,
    titulo: "Hola Mundo en Brainfuck",
    descripcion: "Crea un programa en Brainfuck que imprima 'Hola Mundo' en la consola.",
    nivel: "Student",
    tipo: "Backend",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    recursos: ["https://es.wikipedia.org/wiki/Brainfuck", "https://esolangs.org/wiki/Brainfuck"],
  },
  {
    id: 1002,
    titulo: "Calculadora Básica en Brainfuck",
    descripcion: "Implementa una calculadora que pueda sumar y restar números de un solo dígito.",
    nivel: "Junior",
    tipo: "Backend",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    recursos: ["https://es.wikipedia.org/wiki/Brainfuck", "https://esolangs.org/wiki/Brainfuck"],
  },
  {
    id: 1003,
    titulo: "Generador de Fibonacci en Brainfuck",
    descripcion: "Crea un programa que genere los primeros números de la secuencia de Fibonacci.",
    nivel: "Senior",
    tipo: "Backend",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    recursos: ["https://es.wikipedia.org/wiki/Brainfuck", "https://esolangs.org/wiki/Brainfuck"],
  },
  {
    id: 1004,
    titulo: "Conversor ASCII en Brainfuck",
    descripcion: "Desarrolla un programa que convierta caracteres a sus valores ASCII y viceversa.",
    nivel: "Trainee",
    tipo: "Backend",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    recursos: ["https://es.wikipedia.org/wiki/Brainfuck", "https://esolangs.org/wiki/Brainfuck"],
  },
  {
    id: 1005,
    titulo: "Juego del Ahorcado en Brainfuck",
    descripcion: "Implementa una versión simple del juego del ahorcado en Brainfuck.",
    nivel: "Master",
    tipo: "Game",
    tecnologias: ["Brainfuck"],
    frameworks: [],
    basesdedatos: [],
    recursos: ["https://es.wikipedia.org/wiki/Brainfuck", "https://esolangs.org/wiki/Brainfuck"],
  },
]
