// Definir tipos
import type { ProjectIdea } from "./project-ideas"

// Lista de ideas específicas para videojuegos
export const gameProjectIdeas: ProjectIdea[] = [
  // GDScript - Godot Engine (10 proyectos)
  {
    titulo: "Plataformero 2D con Mecánicas de Física",
    descripcion: "Juego de plataformas 2D con mecánicas de física realistas, niveles progresivos y coleccionables.",
    categoria: "Plataformas",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Puzles con Manipulación de Objetos",
    descripcion: "Juego de puzles donde el jugador manipula objetos para resolver desafíos con física realista.",
    categoria: "Puzles",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Roguelike con Generación Procedural",
    descripcion: "Juego roguelike con niveles generados proceduralmente, combate por turnos y progresión de personaje.",
    categoria: "Roguelike",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Tower Defense con Múltiples Estrategias",
    descripcion: "Juego de defensa de torres con diferentes tipos de enemigos, torres y estrategias de defensa.",
    categoria: "Estrategia",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Aventura Gráfica Point & Click",
    descripcion: "Juego de aventura gráfica con sistema de diálogos, inventario y puzles narrativos.",
    categoria: "Aventura",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "RPG de Mundo Abierto 2D",
    descripcion: "Juego de rol con mundo abierto 2D, sistema de misiones, combate y progresión de personaje.",
    categoria: "RPG",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Shooter Multijugador en Red",
    descripcion: "Juego de disparos multijugador con diferentes modos de juego, armas y mapas.",
    categoria: "Shooter",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Simulador de Gestión de Recursos",
    descripcion:
      "Juego de simulación donde se gestionan recursos, construcciones y economía de una ciudad o civilización.",
    categoria: "Simulación",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Carreras con IA",
    descripcion:
      "Juego de carreras con inteligencia artificial para oponentes, diferentes pistas y vehículos personalizables.",
    categoria: "Carreras",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Ritmo Musical",
    descripcion: "Juego basado en ritmo donde el jugador debe presionar botones al compás de la música.",
    categoria: "Música",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },

  // C# - Unity (10 proyectos)
  {
    titulo: "Plataformero 3D con Habilidades Especiales",
    descripcion: "Juego de plataformas 3D donde el personaje adquiere habilidades especiales para superar obstáculos.",
    categoria: "Plataformas",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Shooter en Primera Persona",
    descripcion: "Juego de disparos en primera persona con diferentes armas, enemigos y niveles.",
    categoria: "Shooter",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Terror con Elementos de Supervivencia",
    descripcion: "Experiencia de terror donde el jugador debe sobrevivir con recursos limitados y resolver misterios.",
    categoria: "Terror",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "RPG de Acción con Sistema de Combos",
    descripcion: "Juego de rol con combate en tiempo real, sistema de combos y progresión de personaje.",
    categoria: "RPG",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Estrategia por Turnos",
    descripcion: "Juego de estrategia por turnos con diferentes unidades, terrenos y condiciones de victoria.",
    categoria: "Estrategia",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Simulador de Física con Construcción",
    descripcion: "Juego de construcción donde los jugadores crean estructuras con física realista.",
    categoria: "Simulación",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Cartas Coleccionables",
    descripcion: "Juego de cartas donde los jugadores coleccionan, construyen mazos y compiten entre sí.",
    categoria: "Cartas",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Mundo Virtual Social",
    descripcion:
      "Plataforma social virtual donde los usuarios pueden interactuar, personalizar avatares y crear contenido.",
    categoria: "Social",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Realidad Aumentada",
    descripcion: "Experiencia de RA donde los jugadores interactúan con elementos virtuales en el mundo real.",
    categoria: "Realidad Aumentada",
    tecnologias: ["C#"],
    frameworks: ["Unity", "ARCore", "ARKit"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego Educativo para Niños",
    descripcion: "Juego educativo con minijuegos que enseñan matemáticas, lenguaje y ciencias a niños.",
    categoria: "Educativo",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },

  // C++ - Unreal Engine (10 proyectos)
  {
    titulo: "Shooter en Tercera Persona con Cobertura",
    descripcion: "Juego de disparos en tercera persona con sistema de cobertura, armas y enemigos variados.",
    categoria: "Shooter",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Mundo Abierto con Vehículos",
    descripcion: "Experiencia de mundo abierto con conducción de vehículos, misiones y exploración.",
    categoria: "Mundo Abierto",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Supervivencia en Primera Persona",
    descripcion: "Experiencia de supervivencia donde el jugador debe gestionar recursos, construir y defenderse.",
    categoria: "Supervivencia",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Peleas 1vs1",
    descripcion: "Juego de combate uno contra uno con diferentes personajes, movimientos especiales y escenarios.",
    categoria: "Lucha",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Simulador de Vuelo Arcade",
    descripcion: "Simulador de vuelo con física simplificada, misiones y diferentes aeronaves.",
    categoria: "Simulación",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Aventura Cinemática",
    descripcion: "Aventura narrativa con decisiones que afectan la historia y secuencias cinemáticas.",
    categoria: "Aventura",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Sigilo y Espionaje",
    descripcion: "Experiencia de sigilo donde el jugador debe infiltrarse, evitar guardias y completar objetivos.",
    categoria: "Sigilo",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Deportes Extremos",
    descripcion: "Simulación de deportes extremos con física realista y diferentes modalidades.",
    categoria: "Deportes",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Horror Psicológico",
    descripcion: "Experiencia de terror psicológico con narrativa profunda y mecánicas de sanidad mental.",
    categoria: "Terror",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Simulador de Física Destructiva",
    descripcion: "Juego centrado en la destrucción de entornos con física realista y efectos visuales.",
    categoria: "Simulación",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },

  // Blueprints - Unreal Engine (5 proyectos)
  {
    titulo: "Juego de Puzles con Manipulación de Tiempo",
    descripcion: "Juego de puzles donde el jugador puede manipular el tiempo para resolver desafíos.",
    categoria: "Puzles",
    tecnologias: ["Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Plataformero 2.5D con Cambio de Perspectiva",
    descripcion: "Juego de plataformas que combina elementos 2D y 3D con mecánicas de cambio de perspectiva.",
    categoria: "Plataformas",
    tecnologias: ["Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Escape Room Virtual",
    descripcion: "Experiencia de escape room en primera persona con puzles y narrativa inmersiva.",
    categoria: "Puzles",
    tecnologias: ["Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Aventura con Diálogos Ramificados",
    descripcion: "Aventura narrativa con sistema de diálogos ramificados que afectan el desarrollo de la historia.",
    categoria: "Aventura",
    tecnologias: ["Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Simulador de Construcción de Bases",
    descripcion: "Juego donde los jugadores construyen y gestionan bases con diferentes recursos y amenazas.",
    categoria: "Simulación",
    tecnologias: ["Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },

  // JavaScript - Phaser (5 proyectos)
  {
    titulo: "Juego de Plataformas HTML5",
    descripcion: "Juego de plataformas 2D para navegadores web con niveles, enemigos y coleccionables.",
    categoria: "Plataformas",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Shooter Top-Down Multijugador",
    descripcion: "Juego de disparos desde vista superior con modo multijugador en tiempo real.",
    categoria: "Shooter",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser", "Socket.io"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Puzles Casual para Móviles",
    descripcion: "Juego casual de puzles para dispositivos móviles con progresión de dificultad.",
    categoria: "Puzles",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Cartas Coleccionables Web",
    descripcion: "Juego de cartas coleccionables para navegadores con modo un jugador y multijugador.",
    categoria: "Cartas",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser", "Socket.io"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Endless Runner con Progresión",
    descripcion: "Juego de carrera infinita con sistema de progresión, desbloqueos y personalización.",
    categoria: "Arcade",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },

  // Rust - Bevy (5 proyectos)
  {
    titulo: "Roguelike con Generación Procedural",
    descripcion: "Juego roguelike con generación procedural de niveles, combate por turnos y elementos de RPG.",
    categoria: "Roguelike",
    tecnologias: ["Rust"],
    frameworks: ["Bevy"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Simulador de Ecosistema",
    descripcion: "Simulación de un ecosistema con diferentes especies que interactúan entre sí y con el entorno.",
    categoria: "Simulación",
    tecnologias: ["Rust"],
    frameworks: ["Bevy"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Estrategia por Turnos",
    descripcion: "Juego de estrategia por turnos con diferentes unidades, terrenos y condiciones de victoria.",
    categoria: "Estrategia",
    tecnologias: ["Rust"],
    frameworks: ["Bevy"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Shooter Arena Multijugador",
    descripcion: "Juego de disparos en arena con modo multijugador y diferentes personajes.",
    categoria: "Shooter",
    tecnologias: ["Rust"],
    frameworks: ["Bevy"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Plataformero 2D con Física Realista",
    descripcion: "Juego de plataformas 2D con física realista y mecánicas de movimiento avanzadas.",
    categoria: "Plataformas",
    tecnologias: ["Rust"],
    frameworks: ["Bevy"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },

  // RPG Maker (5 proyectos)
  {
    titulo: "RPG Clásico por Turnos",
    descripcion: "Juego de rol clásico con combate por turnos, historia épica y múltiples personajes.",
    categoria: "RPG",
    tecnologias: ["JavaScript"],
    frameworks: ["RPG Maker MZ"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Aventura de Terror Psicológico",
    descripcion: "Juego de terror psicológico con énfasis en la narrativa y atmósfera inquietante.",
    categoria: "Terror",
    tecnologias: ["JavaScript"],
    frameworks: ["RPG Maker MV"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Rol Táctico",
    descripcion: "RPG con combate táctico por turnos en cuadrícula con diferentes clases y habilidades.",
    categoria: "RPG Táctico",
    tecnologias: ["JavaScript"],
    frameworks: ["RPG Maker MZ"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Novela Visual con Múltiples Finales",
    descripcion: "Novela visual interactiva con decisiones que afectan la historia y múltiples finales.",
    categoria: "Novela Visual",
    tecnologias: ["JavaScript"],
    frameworks: ["RPG Maker MV"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Rol de Mundo Abierto",
    descripcion: "RPG de mundo abierto con sistema de misiones, comercio y exploración.",
    categoria: "RPG",
    tecnologias: ["JavaScript"],
    frameworks: ["RPG Maker MZ"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },

  // Lua - LÖVE (5 proyectos)
  {
    titulo: "Plataformero 2D Minimalista",
    descripcion: "Juego de plataformas 2D con estética minimalista y mecánicas de juego precisas.",
    categoria: "Plataformas",
    tecnologias: ["Lua"],
    frameworks: ["LÖVE"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Shooter Top-Down con Generación Procedural",
    descripcion: "Juego de disparos desde vista superior con niveles generados proceduralmente.",
    categoria: "Shooter",
    tecnologias: ["Lua"],
    frameworks: ["LÖVE"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Puzles Basado en Física",
    descripcion: "Juego de puzles donde el jugador manipula objetos con física para resolver desafíos.",
    categoria: "Puzles",
    tecnologias: ["Lua"],
    frameworks: ["LÖVE"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Ritmo Musical",
    descripcion: "Juego basado en ritmo donde el jugador debe presionar botones al compás de la música.",
    categoria: "Música",
    tecnologias: ["Lua"],
    frameworks: ["LÖVE"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Roguelike con Combate por Turnos",
    descripcion: "Juego roguelike con combate por turnos, generación procedural y elementos permanentes.",
    categoria: "Roguelike",
    tecnologias: ["Lua"],
    frameworks: ["LÖVE"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },

  // Python - Pygame (5 proyectos)
  {
    titulo: "Juego de Plataformas Simple",
    descripcion: "Juego de plataformas 2D con niveles, enemigos básicos y coleccionables.",
    categoria: "Plataformas",
    tecnologias: ["Python"],
    frameworks: ["Pygame"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Clon de Snake con Variaciones",
    descripcion: "Versión del clásico juego Snake con variaciones en mecánicas y power-ups.",
    categoria: "Arcade",
    tecnologias: ["Python"],
    frameworks: ["Pygame"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Estrategia por Turnos",
    descripcion: "Juego de estrategia por turnos con diferentes unidades y condiciones de victoria.",
    categoria: "Estrategia",
    tecnologias: ["Python"],
    frameworks: ["Pygame"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Shooter Espacial 2D",
    descripcion: "Juego de disparos espacial con diferentes naves, enemigos y power-ups.",
    categoria: "Shooter",
    tecnologias: ["Python"],
    frameworks: ["Pygame"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Puzles Tipo Sokoban",
    descripcion: "Juego de puzles donde el jugador empuja cajas para resolver niveles.",
    categoria: "Puzles",
    tecnologias: ["Python"],
    frameworks: ["Pygame"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },

  // C++ - Custom Engine (5 proyectos)
  {
    titulo: "Motor de Juegos 2D desde Cero",
    descripcion: "Desarrollo de un motor de juegos 2D básico con renderizado, física y entrada de usuario.",
    categoria: "Motor de Juegos",
    tecnologias: ["C++"],
    frameworks: ["OpenGL", "SDL"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Shooter en Primera Persona Minimalista",
    descripcion: "Juego de disparos en primera persona con gráficos minimalistas y mecánicas básicas.",
    categoria: "Shooter",
    tecnologias: ["C++"],
    frameworks: ["OpenGL", "Bullet Physics"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Simulador de Física Avanzada",
    descripcion: "Simulación de física con fluidos, cuerpos rígidos y deformables en tiempo real.",
    categoria: "Simulación",
    tecnologias: ["C++"],
    frameworks: ["OpenGL", "PhysX"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Estrategia en Tiempo Real",
    descripcion: "Juego de estrategia en tiempo real con unidades, recursos y construcción de bases.",
    categoria: "Estrategia",
    tecnologias: ["C++"],
    frameworks: ["SDL", "Custom Engine"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Emulador de Consola Retro",
    descripcion: "Emulador de una consola de videojuegos retro con soporte para ROMs originales.",
    categoria: "Emulación",
    tecnologias: ["C++"],
    frameworks: ["SDL"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },

  // TypeScript - Three.js (5 proyectos)
  {
    titulo: "Juego de Aventura 3D para Navegadores",
    descripcion: "Aventura 3D para navegadores web con exploración, puzles y narrativa.",
    categoria: "Aventura",
    tecnologias: ["TypeScript"],
    frameworks: ["Three.js"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Simulador de Conducción Web",
    descripcion: "Simulador de conducción 3D para navegadores con física realista y diferentes vehículos.",
    categoria: "Simulación",
    tecnologias: ["TypeScript"],
    frameworks: ["Three.js", "Cannon.js"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Construcción y Creatividad",
    descripcion: "Experiencia creativa donde los jugadores construyen estructuras en un entorno 3D.",
    categoria: "Creatividad",
    tecnologias: ["TypeScript"],
    frameworks: ["Three.js"],
    basesdedatos: ["Firebase"],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Shooter en Primera Persona para Web",
    descripcion: "Juego de disparos en primera persona optimizado para navegadores web.",
    categoria: "Shooter",
    tecnologias: ["TypeScript"],
    frameworks: ["Three.js", "Cannon.js"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Experiencia Interactiva Musical",
    descripcion:
      "Experiencia audiovisual interactiva donde los usuarios crean música a través de la interacción con objetos 3D.",
    categoria: "Música",
    tecnologias: ["TypeScript"],
    frameworks: ["Three.js", "Tone.js"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
]
