// Definir tipos
import type { ProjectIdea } from "./project-ideas"

// Lista de ideas para nivel Student
export const projectIdeasStudent: ProjectIdea[] = [
  // HTML/CSS - 20 proyectos
  {
    titulo: "Página Personal Simple",
    descripcion: "Crea una página web personal con información básica, foto y enlaces a redes sociales.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Tarjeta de Presentación Digital",
    descripcion: "Diseña una tarjeta de presentación digital con tus datos de contacto y habilidades.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Página de Tributo",
    descripcion: "Crea una página de tributo a una persona que admires con información y fotos.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Formulario de Registro",
    descripcion: "Diseña un formulario de registro con validación visual de campos.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Página de Producto",
    descripcion: "Crea una página que muestre un producto con descripción, precio y botón de compra.",
    categoria: "E-commerce",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Galería de Imágenes",
    descripcion: "Diseña una galería de imágenes con cuadrícula responsive.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Menú de Restaurante",
    descripcion: "Crea un menú digital para un restaurante con categorías y precios.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Página de Error 404",
    descripcion: "Diseña una página de error 404 creativa y funcional.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Calendario Mensual",
    descripcion: "Crea un calendario mensual con diseño atractivo usando tablas o grid.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Página de Precios",
    descripcion: "Diseña una página de comparación de planes y precios para un servicio.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Testimonios de Clientes",
    descripcion: "Crea una sección de testimonios con fotos y citas de clientes.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Página de Preguntas Frecuentes",
    descripcion: "Diseña una página de FAQ con preguntas y respuestas desplegables.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Tarjetas de Perfil",
    descripcion: "Crea tarjetas de perfil para miembros de un equipo con foto e información.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Barra de Navegación Responsive",
    descripcion: "Diseña una barra de navegación que se adapte a diferentes tamaños de pantalla.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Página de Contacto",
    descripcion: "Crea una página de contacto con formulario y mapa de ubicación.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Pie de Página Completo",
    descripcion: "Diseña un pie de página con enlaces, información de contacto y redes sociales.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Página de Características de Producto",
    descripcion: "Crea una página que muestre las características de un producto con iconos y descripciones.",
    categoria: "E-commerce",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Cronología Personal",
    descripcion: "Diseña una cronología visual de eventos importantes en tu vida o carrera.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Página de Próximos Eventos",
    descripcion: "Crea una página que muestre próximos eventos con fechas y descripciones.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Portafolio Básico",
    descripcion: "Diseña un portafolio simple para mostrar tus proyectos con imágenes y descripciones.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },

  // JavaScript - 20 proyectos
  {
    titulo: "Contador Simple",
    descripcion: "Crea un contador que permita incrementar, decrementar y resetear un valor.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Reloj Digital",
    descripcion: "Desarrolla un reloj digital que muestre la hora actual y se actualice cada segundo.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Calculadora Básica",
    descripcion: "Crea una calculadora que realice operaciones aritméticas básicas.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Lista de Tareas Simple",
    descripcion: "Desarrolla una aplicación para añadir, marcar como completadas y eliminar tareas.",
    categoria: "Productividad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Cambiador de Colores",
    descripcion: "Crea una aplicación que cambie el color de fondo al hacer clic en un botón.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Validador de Formulario",
    descripcion: "Desarrolla un formulario con validación de campos en tiempo real.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Piedra, Papel o Tijera",
    descripcion: "Crea un juego simple de piedra, papel o tijera contra la computadora.",
    categoria: "Juego",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Generador de Citas",
    descripcion: "Desarrolla una aplicación que muestre citas aleatorias al hacer clic en un botón.",
    categoria: "Entretenimiento",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Acordeón de Preguntas Frecuentes",
    descripcion: "Crea un acordeón interactivo para mostrar preguntas y respuestas.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Temporizador Simple",
    descripcion: "Desarrolla un temporizador de cuenta regresiva con inicio, pausa y reinicio.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Carrusel de Imágenes",
    descripcion: "Crea un carrusel para mostrar imágenes con navegación manual.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Conversor de Unidades",
    descripcion: "Desarrolla un conversor para diferentes unidades de medida.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Adivinanza",
    descripcion: "Crea un juego donde el usuario debe adivinar un número aleatorio.",
    categoria: "Juego",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Filtro de Búsqueda",
    descripcion: "Desarrolla un filtro de búsqueda para una lista de elementos.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Modal Simple",
    descripcion: "Crea ventanas modales que se abran y cierren con animaciones.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Calculadora de Propinas",
    descripcion: "Desarrolla una calculadora que determine la propina basada en el total de la cuenta.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Memoria",
    descripcion: "Crea un juego de memoria con cartas que deben emparejarse.",
    categoria: "Juego",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Verificador de Palíndromos",
    descripcion: "Desarrolla una aplicación que verifique si una palabra es un palíndromo.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Generador de Contraseñas",
    descripcion: "Crea un generador de contraseñas aleatorias con opciones configurables.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Contador de Palabras",
    descripcion: "Desarrolla una aplicación que cuente palabras y caracteres en un texto.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },

  // React - 20 proyectos
  {
    titulo: "Lista de Tareas con React",
    descripcion: "Crea una aplicación de lista de tareas usando componentes de React.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Contador con Hooks",
    descripcion: "Desarrolla un contador simple utilizando los hooks de React.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Buscador de Películas",
    descripcion: "Crea una aplicación para buscar películas usando una API pública.",
    categoria: "Entretenimiento",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Calculadora React",
    descripcion: "Desarrolla una calculadora funcional con React.",
    categoria: "Utilidad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación del Clima",
    descripcion: "Crea una aplicación que muestre el clima actual usando una API.",
    categoria: "Utilidad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Galería de Fotos",
    descripcion: "Desarrolla una galería de fotos con filtros y vista previa.",
    categoria: "Multimedia",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Formulario con Validación",
    descripcion: "Crea un formulario con validación de campos usando React.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Lista de Compras",
    descripcion: "Desarrolla una aplicación para gestionar listas de compras.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Temporizador Pomodoro",
    descripcion: "Crea un temporizador para la técnica Pomodoro con React.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Preguntas y Respuestas",
    descripcion: "Desarrolla un juego de trivia con preguntas de una API.",
    categoria: "Juego",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Gestor de Notas",
    descripcion: "Crea una aplicación para tomar y organizar notas.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Reloj Mundial",
    descripcion: "Desarrolla un reloj que muestre la hora en diferentes zonas horarias.",
    categoria: "Utilidad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Buscador de Recetas",
    descripcion: "Crea una aplicación para buscar recetas de cocina usando una API.",
    categoria: "Alimentación",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Conversor de Monedas",
    descripcion: "Desarrolla un conversor de divisas con tasas actualizadas.",
    categoria: "Finanzas",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Calendario de Eventos",
    descripcion: "Crea un calendario para gestionar eventos y recordatorios.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Memoria",
    descripcion: "Desarrolla un juego de memoria con cartas usando React.",
    categoria: "Juego",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Gestor de Contraseñas",
    descripcion: "Crea una aplicación para almacenar y gestionar contraseñas.",
    categoria: "Seguridad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Tablero Kanban Simple",
    descripcion: "Desarrolla un tablero Kanban básico para gestionar tareas.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Buscador de Empleos",
    descripcion: "Crea una aplicación para buscar ofertas de trabajo usando una API.",
    categoria: "Empleo",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Perfil de Usuario",
    descripcion: "Desarrolla una página de perfil de usuario con edición de datos.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },

  // Python - 20 proyectos
  {
    titulo: "Calculadora de Consola",
    descripcion: "Crea una calculadora simple que funcione en la consola.",
    categoria: "Utilidad",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Generador de Contraseñas",
    descripcion: "Desarrolla un programa que genere contraseñas aleatorias.",
    categoria: "Seguridad",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Conversor de Unidades",
    descripcion: "Crea un programa para convertir entre diferentes unidades de medida.",
    categoria: "Utilidad",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Adivinanza",
    descripcion: "Desarrolla un juego donde el usuario debe adivinar un número aleatorio.",
    categoria: "Juego",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Lista de Tareas de Consola",
    descripcion: "Crea una aplicación de línea de comandos para gestionar tareas.",
    categoria: "Productividad",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Reloj Digital",
    descripcion: "Desarrolla un reloj digital que muestre la hora actual en la consola.",
    categoria: "Utilidad",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora de IMC",
    descripcion: "Crea un programa que calcule el índice de masa corporal.",
    categoria: "Salud",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Piedra, Papel o Tijera",
    descripcion: "Desarrolla un juego simple de piedra, papel o tijera contra la computadora.",
    categoria: "Juego",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Contador de Palabras",
    descripcion: "Crea un programa que cuente palabras y caracteres en un texto.",
    categoria: "Utilidad",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Simulador de Dado",
    descripcion: "Desarrolla un programa que simule el lanzamiento de dados.",
    categoria: "Juego",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Conversor de Monedas",
    descripcion: "Crea un programa para convertir entre diferentes monedas.",
    categoria: "Finanzas",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora de Edad",
    descripcion: "Desarrolla un programa que calcule la edad exacta a partir de la fecha de nacimiento.",
    categoria: "Utilidad",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Generador de Historias Aleatorias",
    descripcion: "Crea un programa que genere historias aleatorias combinando elementos predefinidos.",
    categoria: "Entretenimiento",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Temporizador Simple",
    descripcion: "Desarrolla un temporizador de cuenta regresiva en la consola.",
    categoria: "Utilidad",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego del Ahorcado",
    descripcion: "Crea el clásico juego del ahorcado en la consola.",
    categoria: "Juego",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora de Propinas",
    descripcion: "Desarrolla un programa que calcule propinas basadas en el total de la cuenta.",
    categoria: "Finanzas",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Generador de Citas",
    descripcion: "Crea un programa que muestre citas aleatorias de una lista predefinida.",
    categoria: "Entretenimiento",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Verificador de Palíndromos",
    descripcion: "Desarrolla un programa que verifique si una palabra es un palíndromo.",
    categoria: "Utilidad",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora de Calorías",
    descripcion: "Crea un programa que calcule las calorías necesarias según peso, altura y actividad física.",
    categoria: "Salud",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Agenda de Contactos",
    descripcion: "Desarrolla una agenda simple para guardar y buscar contactos.",
    categoria: "Productividad",
    tecnologias: ["Python"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },

  // Java - 20 proyectos
  {
    titulo: "Calculadora Simple",
    descripcion: "Crea una calculadora con interfaz gráfica básica usando Swing.",
    categoria: "Utilidad",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Conversor de Unidades",
    descripcion: "Desarrolla un programa para convertir entre diferentes unidades de medida.",
    categoria: "Utilidad",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Adivinanza",
    descripcion: "Crea un juego donde el usuario debe adivinar un número aleatorio.",
    categoria: "Juego",
    tecnologias: ["Java"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Lista de Tareas",
    descripcion: "Desarrolla una aplicación para gestionar tareas diarias.",
    categoria: "Productividad",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Simulador de Dado",
    descripcion: "Crea un programa que simule el lanzamiento de dados con interfaz gráfica.",
    categoria: "Juego",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora de IMC",
    descripcion: "Desarrolla un programa que calcule el índice de masa corporal.",
    categoria: "Salud",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Piedra, Papel o Tijera",
    descripcion: "Crea un juego simple de piedra, papel o tijera contra la computadora.",
    categoria: "Juego",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Editor de Texto Simple",
    descripcion: "Desarrolla un editor de texto básico con funciones de guardar y abrir archivos.",
    categoria: "Utilidad",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Reloj Digital",
    descripcion: "Crea un reloj digital con interfaz gráfica que muestre la hora actual.",
    categoria: "Utilidad",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Agenda de Contactos",
    descripcion: "Desarrolla una agenda para guardar y buscar contactos.",
    categoria: "Productividad",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora de Préstamos",
    descripcion: "Crea un programa que calcule pagos mensuales de préstamos.",
    categoria: "Finanzas",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Memoria",
    descripcion: "Desarrolla un juego de memoria con cartas que deben emparejarse.",
    categoria: "Juego",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Conversor de Monedas",
    descripcion: "Crea un programa para convertir entre diferentes monedas.",
    categoria: "Finanzas",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Temporizador Pomodoro",
    descripcion: "Desarrolla un temporizador para la técnica Pomodoro.",
    categoria: "Productividad",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Generador de Contraseñas",
    descripcion: "Crea un programa que genere contraseñas aleatorias.",
    categoria: "Seguridad",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora de Calorías",
    descripcion: "Desarrolla un programa que calcule las calorías necesarias según datos físicos.",
    categoria: "Salud",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego del Ahorcado",
    descripcion: "Crea el clásico juego del ahorcado con interfaz gráfica.",
    categoria: "Juego",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calendario Simple",
    descripcion: "Desarrolla un calendario que muestre el mes actual y permita navegar entre meses.",
    categoria: "Utilidad",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Reproductor de Música Básico",
    descripcion: "Crea un reproductor de música simple que pueda reproducir archivos MP3.",
    categoria: "Multimedia",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Dibujo Simple",
    descripcion: "Desarrolla una aplicación que permita dibujar formas básicas.",
    categoria: "Gráficos",
    tecnologias: ["Java"],
    frameworks: ["Swing"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },

  // C# - 20 proyectos
  {
    titulo: "Calculadora Windows Forms",
    descripcion: "Crea una calculadora con interfaz gráfica usando Windows Forms.",
    categoria: "Utilidad",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Lista de Tareas",
    descripcion: "Desarrolla una aplicación para gestionar tareas diarias.",
    categoria: "Productividad",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Conversor de Unidades",
    descripcion: "Crea un programa para convertir entre diferentes unidades de medida.",
    categoria: "Utilidad",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Adivinanza",
    descripcion: "Desarrolla un juego donde el usuario debe adivinar un número aleatorio.",
    categoria: "Juego",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Editor de Texto Simple",
    descripcion: "Crea un editor de texto básico con funciones de guardar y abrir archivos.",
    categoria: "Utilidad",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Reloj Digital",
    descripcion: "Desarrolla un reloj digital que muestre la hora actual.",
    categoria: "Utilidad",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora de IMC",
    descripcion: "Crea un programa que calcule el índice de masa corporal.",
    categoria: "Salud",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Piedra, Papel o Tijera",
    descripcion: "Desarrolla un juego simple de piedra, papel o tijera contra la computadora.",
    categoria: "Juego",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Agenda de Contactos",
    descripcion: "Crea una agenda para guardar y buscar contactos.",
    categoria: "Productividad",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Simulador de Dado",
    descripcion: "Desarrolla un programa que simule el lanzamiento de dados.",
    categoria: "Juego",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora de Préstamos",
    descripcion: "Crea un programa que calcule pagos mensuales de préstamos.",
    categoria: "Finanzas",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Generador de Contraseñas",
    descripcion: "Desarrolla un programa que genere contraseñas aleatorias.",
    categoria: "Seguridad",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Memoria",
    descripcion: "Crea un juego de memoria con cartas que deben emparejarse.",
    categoria: "Juego",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Conversor de Monedas",
    descripcion: "Desarrolla un programa para convertir entre diferentes monedas.",
    categoria: "Finanzas",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Temporizador Pomodoro",
    descripcion: "Crea un temporizador para la técnica Pomodoro.",
    categoria: "Productividad",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calculadora de Calorías",
    descripcion: "Desarrolla un programa que calcule las calorías necesarias según datos físicos.",
    categoria: "Salud",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego del Ahorcado",
    descripcion: "Crea el clásico juego del ahorcado con interfaz gráfica.",
    categoria: "Juego",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Reproductor de Música Básico",
    descripcion: "Desarrolla un reproductor de música simple que pueda reproducir archivos MP3.",
    categoria: "Multimedia",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Dibujo Simple",
    descripcion: "Crea una aplicación que permita dibujar formas básicas.",
    categoria: "Gráficos",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Calendario Simple",
    descripcion: "Desarrolla un calendario que muestre el mes actual y permita navegar entre meses.",
    categoria: "Utilidad",
    tecnologias: ["C#"],
    frameworks: ["Windows Forms"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación de Escritorio",
  },

  // Videojuegos - 20 proyectos
  {
    titulo: "Juego de Pong",
    descripcion: "Crea una versión simple del clásico juego Pong.",
    categoria: "Arcade",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Snake",
    descripcion: "Desarrolla el clásico juego de la serpiente que crece al comer.",
    categoria: "Arcade",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Memoria",
    descripcion: "Crea un juego de memoria con cartas que deben emparejarse.",
    categoria: "Puzles",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Plataformas Simple",
    descripcion: "Desarrolla un juego de plataformas básico con un personaje que salta.",
    categoria: "Plataformas",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Preguntas y Respuestas",
    descripcion: "Crea un juego de trivia con preguntas de diferentes categorías.",
    categoria: "Educativo",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Breakout",
    descripcion: "Desarrolla una versión del clásico juego Breakout o Arkanoid.",
    categoria: "Arcade",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Carreras Simple",
    descripcion: "Crea un juego de carreras básico con obstáculos.",
    categoria: "Carreras",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Laberinto",
    descripcion: "Desarrolla un juego donde el jugador debe encontrar la salida de un laberinto.",
    categoria: "Puzles",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Disparos Espaciales",
    descripcion: "Crea un juego de disparos espaciales con naves y enemigos.",
    categoria: "Shooter",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Tres en Raya",
    descripcion: "Desarrolla el clásico juego de tres en raya (tic-tac-toe).",
    categoria: "Puzles",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Whack-a-Mole",
    descripcion: "Crea un juego donde debes golpear topos que aparecen aleatoriamente.",
    categoria: "Arcade",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Flappy Bird",
    descripcion: "Desarrolla un clon simple del famoso juego Flappy Bird.",
    categoria: "Arcade",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Tetris",
    descripcion: "Crea una versión básica del clásico juego Tetris.",
    categoria: "Puzles",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Cartas Simple",
    descripcion: "Desarrolla un juego de cartas básico como Blackjack o Memoria.",
    categoria: "Cartas",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Esquivar Obstáculos",
    descripcion: "Crea un juego donde el jugador debe esquivar obstáculos que caen.",
    categoria: "Arcade",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Rompecabezas",
    descripcion: "Desarrolla un juego de rompecabezas con imágenes que se dividen en piezas.",
    categoria: "Puzles",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Pinball Simple",
    descripcion: "Crea una versión básica de un juego de pinball.",
    categoria: "Arcade",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Palabras",
    descripcion: "Desarrolla un juego tipo Scrabble o sopa de letras.",
    categoria: "Educativo",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Simulación Simple",
    descripcion: "Crea un juego de simulación básico como una granja o una tienda.",
    categoria: "Simulación",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Ritmo",
    descripcion: "Desarrolla un juego donde el jugador debe presionar teclas al ritmo de la música.",
    categoria: "Música",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Videojuego",
  },

  // Bases de datos - 20 proyectos
  {
    titulo: "Sistema de Gestión de Biblioteca",
    descripcion: "Crea una aplicación para gestionar libros, préstamos y usuarios de una biblioteca.",
    categoria: "Educación",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["SQLite"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Gestor de Contactos",
    descripcion: "Desarrolla una aplicación para almacenar y gestionar contactos.",
    categoria: "Productividad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Lista de Tareas con Persistencia",
    descripcion: "Crea una aplicación de tareas que guarde los datos en una base de datos.",
    categoria: "Productividad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Inventario Simple",
    descripcion: "Desarrolla un sistema básico de inventario para productos.",
    categoria: "Negocios",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Registro de Gastos",
    descripcion: "Crea una aplicación para registrar y categorizar gastos personales.",
    categoria: "Finanzas",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Gestor de Notas",
    descripcion: "Desarrolla una aplicación para tomar y organizar notas con categorías.",
    categoria: "Productividad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Registro de Ejercicios",
    descripcion: "Crea una aplicación para registrar rutinas de ejercicios y progreso.",
    categoria: "Salud",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Catálogo de Películas",
    descripcion: "Desarrolla una aplicación para catalogar películas vistas y por ver.",
    categoria: "Entretenimiento",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Registro de Recetas",
    descripcion: "Crea una aplicación para guardar y buscar recetas de cocina.",
    categoria: "Alimentación",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Agenda de Citas",
    descripcion: "Desarrolla una aplicación para gestionar citas y recordatorios.",
    categoria: "Productividad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Registro de Libros Leídos",
    descripcion: "Crea una aplicación para registrar libros leídos con valoraciones.",
    categoria: "Educación",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Gestor de Contraseñas Simple",
    descripcion: "Desarrolla una aplicación para almacenar contraseñas de forma segura.",
    categoria: "Seguridad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Registro de Actividades Diarias",
    descripcion: "Crea una aplicación para registrar actividades diarias y hábitos.",
    categoria: "Productividad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Catálogo de Música",
    descripcion: "Desarrolla una aplicación para catalogar música por artistas y géneros.",
    categoria: "Entretenimiento",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Registro de Compras",
    descripcion: "Crea una aplicación para registrar compras y gastos por categorías.",
    categoria: "Finanzas",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Gestor de Proyectos Simple",
    descripcion: "Desarrolla una aplicación para gestionar proyectos pequeños y tareas.",
    categoria: "Productividad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Diario Personal",
    descripcion: "Crea una aplicación de diario personal con entradas por fecha.",
    categoria: "Productividad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Registro de Medicamentos",
    descripcion: "Desarrolla una aplicación para registrar medicamentos y horarios.",
    categoria: "Salud",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Catálogo de Videojuegos",
    descripcion: "Crea una aplicación para catalogar videojuegos por plataforma y género.",
    categoria: "Entretenimiento",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Registro de Plantas",
    descripcion: "Desarrolla una aplicación para registrar plantas y sus cuidados.",
    categoria: "Hogar",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["IndexedDB"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
]
