// Definir tipos
export interface ProjectIdea {
  titulo: string
  descripcion: string
  categoria: string
  tecnologias: string[]
  frameworks: string[]
  basesdedatos: string[]
  nivel: "Student" | "Trainee" | "Junior" | "Senior" | "Master"
  tipo:
    | "Aplicación Web"
    | "Aplicación Móvil"
    | "Aplicación de Escritorio"
    | "Videojuego"
    | "Aplicación de Consola"
    | "API"
    | "Programación Esotérica"
    | "Backend"
    | "Frontend"
    | "Fullstack"
  id?: string
  nombre?: string
  baseDatos?: string[]
  caracteristicas?: string[]
  complejidad?: number
}

// Importar ideas adicionales
import { gameProjectIdeas } from "./project-ideas-games"
import { projectIdeasStudent } from "./project-ideas-student"
import { additionalLanguages } from "./additional-languages"
import { additionalLanguagesFrameworks } from "./additional-languages-frameworks"
import { additionalLanguagesTwo } from "./additional-languages-two"
// Import the additional project ideas
import { additionalProjectIdeas } from "./additional-project-ideas"
// Import combination project ideas
import combinationProjectIdeas from "./project-ideas-combinations"

// Función para normalizar las ideas de proyectos
const normalizeProjectIdea = (idea: any): ProjectIdea => {
  return {
    titulo: idea.titulo || idea.nombre || "Proyecto sin título",
    descripcion: idea.descripcion || "Sin descripción",
    categoria: idea.categoria || "General",
    tecnologias: idea.tecnologias || [],
    frameworks: idea.frameworks || [],
    basesdedatos: idea.basesdedatos || idea.baseDatos || [],
    nivel: idea.nivel || "Junior",
    tipo: idea.tipo || "Aplicación Web",
    id: idea.id,
    nombre: idea.nombre,
    baseDatos: idea.baseDatos,
    caracteristicas: idea.caracteristicas,
    complejidad: idea.complejidad,
  }
}

// Normalizar y combinar todas las ideas de proyectos
const normalizeIdeas = (ideas: any[]): ProjectIdea[] => {
  return ideas.map(normalizeProjectIdea)
}

// Modificar la parte donde se combinan todas las ideas de proyectos
// Combinar todas las ideas de proyectos
export const projectIdeas = [
  ...normalizeIdeas(gameProjectIdeas || []),
  ...normalizeIdeas(projectIdeasStudent || []),
  ...normalizeIdeas(additionalLanguages || []),
  ...normalizeIdeas(additionalLanguagesFrameworks || []),
  ...normalizeIdeas(additionalLanguagesTwo || []),
  ...normalizeIdeas(additionalProjectIdeas || []),
  ...normalizeIdeas(combinationProjectIdeas || []),
  // Ideas originales
  {
    id: "1",
    titulo: "Sistema de Gestión de Inventario",
    nombre: "Sistema de Gestión de Inventario",
    descripcion:
      "Desarrolla un sistema para gestionar el inventario de una tienda, con funcionalidades para añadir, editar y eliminar productos, así como para realizar un seguimiento de las existencias.",
    nivel: "Junior",
    tipo: "Aplicación Web",
    tecnologias: ["JavaScript", "React", "Node.js"],
    frameworks: ["Express"],
    basesdedatos: ["MongoDB"],
    baseDatos: ["MongoDB"],
    caracteristicas: ["CRUD", "Autenticación", "Reportes"],
    complejidad: 3,
    categoria: "Negocios",
  },
  {
    titulo: "Planificador de Viajes Interactivo",
    descripcion:
      "Una aplicación que permite a los usuarios planificar viajes con un mapa interactivo, guardar lugares favoritos y crear itinerarios personalizados.",
    categoria: "Planificación",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Gestor de Tareas con Drag & Drop",
    descripcion:
      "Aplicación de gestión de tareas con funcionalidad de arrastrar y soltar para organizar tareas en diferentes estados.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["Vue.js"],
    basesdedatos: ["Firebase"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Streaming de Música",
    descripcion:
      "Servicio para que músicos independientes compartan su música y los oyentes descubran nuevos artistas locales.",
    categoria: "Multimedia",
    tecnologias: ["JavaScript"],
    frameworks: ["Angular", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Preguntas y Respuestas Multijugador",
    descripcion: "Juego en tiempo real donde los jugadores compiten respondiendo preguntas de diferentes categorías.",
    categoria: "Juego",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser.js", "Socket.io"],
    basesdedatos: ["Redis"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Dashboard de Analíticas para Redes Sociales",
    descripcion: "Herramienta para visualizar y analizar datos de redes sociales con gráficos interactivos.",
    categoria: "Marketing",
    tecnologias: ["JavaScript"],
    frameworks: ["D3.js", "Express"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Notas con Markdown",
    descripcion: "Editor de notas que soporta Markdown con vista previa en tiempo real y organización por categorías.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: ["IndexedDB"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Cursos Online",
    descripcion: "Sistema para crear y consumir cursos online con videos, cuestionarios y seguimiento de progreso.",
    categoria: "Educación",
    tecnologias: ["JavaScript"],
    frameworks: ["Next.js"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Chat en Tiempo Real",
    descripcion: "Chat con salas temáticas, mensajes privados y soporte para compartir archivos.",
    categoria: "Comunicación",
    tecnologias: ["JavaScript"],
    frameworks: ["Socket.io", "Express"],
    basesdedatos: ["Firebase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Editor de Código Colaborativo",
    descripcion: "Herramienta para programar en tiempo real con múltiples usuarios y resaltado de sintaxis.",
    categoria: "Desarrollo",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Socket.io"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Clima con Geolocalización",
    descripcion: "Muestra el clima actual y pronóstico basado en la ubicación del usuario con mapas interactivos.",
    categoria: "Utilidad",
    tecnologias: ["JavaScript"],
    frameworks: ["Vue.js"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Comercio Social",
    descripcion: "Combina redes sociales con e-commerce para permitir compras basadas en recomendaciones sociales.",
    categoria: "E-commerce",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Node.js"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Herramienta de Visualización de Datos",
    descripcion: "Aplicación para crear gráficos interactivos y visualizaciones a partir de conjuntos de datos.",
    categoria: "Análisis de Datos",
    tecnologias: ["JavaScript"],
    frameworks: ["D3.js", "React"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Reservas para Eventos",
    descripcion: "Plataforma para gestionar reservas y entradas para eventos con selección de asientos.",
    categoria: "Eventos",
    tecnologias: ["JavaScript"],
    frameworks: ["Vue.js", "Express"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },

  // TypeScript - 10 proyectos
  {
    titulo: "Sistema de Gestión de Proyectos",
    descripcion:
      "Plataforma completa para gestionar proyectos, tareas, recursos y seguimiento de tiempo con informes detallados.",
    categoria: "Productividad",
    tecnologias: ["TypeScript"],
    frameworks: ["Angular", "NestJS"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "E-commerce con Pasarela de Pagos",
    descripcion: "Tienda online completa con catálogo de productos, carrito de compras y procesamiento de pagos.",
    categoria: "E-commerce",
    tecnologias: ["TypeScript"],
    frameworks: ["Next.js"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "CRM para Pequeñas Empresas",
    descripcion: "Sistema de gestión de relaciones con clientes con seguimiento de ventas, contactos y oportunidades.",
    categoria: "Negocios",
    tecnologias: ["TypeScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MySQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Blogs con Análisis SEO",
    descripcion: "Sistema de blogs con editor WYSIWYG, análisis SEO en tiempo real y estadísticas de lectores.",
    categoria: "Contenido",
    tecnologias: ["TypeScript"],
    frameworks: ["Next.js"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Finanzas Personales",
    descripcion: "Herramienta para seguimiento de gastos, presupuestos y visualización de hábitos financieros.",
    categoria: "Finanzas",
    tecnologias: ["TypeScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Reservas para Restaurantes",
    descripcion: "Plataforma para gestionar reservas, mesas y pedidos en restaurantes con panel de administración.",
    categoria: "Servicios",
    tecnologias: ["TypeScript"],
    frameworks: ["Angular", "NestJS"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Red Social para Profesionales",
    descripcion: "Plataforma para networking profesional con perfiles, mensajería y publicación de contenido.",
    categoria: "Red Social",
    tecnologias: ["TypeScript"],
    frameworks: ["React", "GraphQL"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Seguimiento de Hábitos",
    descripcion: "Herramienta para establecer y monitorear hábitos diarios con estadísticas y recordatorios.",
    categoria: "Productividad",
    tecnologias: ["TypeScript"],
    frameworks: ["React Native"],
    basesdedatos: ["Firebase"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Dashboard de IoT",
    descripcion: "Panel para visualizar y controlar dispositivos IoT con gráficos en tiempo real y alertas.",
    categoria: "IoT",
    tecnologias: ["TypeScript"],
    frameworks: ["React", "Socket.io"],
    basesdedatos: ["InfluxDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Aprendizaje de Idiomas",
    descripcion: "Aplicación para aprender idiomas con ejercicios interactivos, reconocimiento de voz y gamificación.",
    categoria: "Educación",
    tecnologias: ["TypeScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Documentos",
    descripcion: "Plataforma para almacenar, organizar y compartir documentos con control de versiones.",
    categoria: "Productividad",
    tecnologias: ["TypeScript"],
    frameworks: ["Angular", "NestJS"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Videoconferencias",
    descripcion: "Plataforma para realizar videollamadas con múltiples participantes, chat y compartir pantalla.",
    categoria: "Comunicación",
    tecnologias: ["TypeScript"],
    frameworks: ["React", "WebRTC"],
    basesdedatos: ["Redis"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Herramienta de Automatización de Marketing",
    descripcion:
      "Sistema para automatizar campañas de marketing por email y redes sociales con análisis de resultados.",
    categoria: "Marketing",
    tecnologias: ["TypeScript"],
    frameworks: ["Vue.js", "Express"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Python - 10 proyectos
  {
    titulo: "Sistema de Recomendación de Contenido",
    descripcion: "Plataforma que recomienda películas, libros o música basándose en preferencias del usuario.",
    categoria: "IA",
    tecnologias: ["Python"],
    frameworks: ["Django", "TensorFlow"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Analizador de Sentimientos en Redes Sociales",
    descripcion: "Herramienta que analiza el sentimiento de publicaciones en redes sociales sobre temas específicos.",
    categoria: "Análisis de Datos",
    tecnologias: ["Python"],
    frameworks: ["Flask", "NLTK"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Bot de Trading Automatizado",
    descripcion: "Sistema que ejecuta operaciones de trading basadas en algoritmos y análisis técnico.",
    categoria: "Finanzas",
    tecnologias: ["Python"],
    frameworks: ["FastAPI", "Pandas"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Plataforma de Gestión de Inventario",
    descripcion: "Sistema para gestionar inventario con seguimiento de stock, proveedores y generación de informes.",
    categoria: "Negocios",
    tecnologias: ["Python"],
    frameworks: ["Django"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Asistente Virtual con Reconocimiento de Voz",
    descripcion: "Asistente que responde a comandos de voz para realizar tareas como búsquedas o programar eventos.",
    categoria: "IA",
    tecnologias: ["Python"],
    frameworks: ["Flask", "TensorFlow"],
    basesdedatos: ["SQLite"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Aplicación de Reconocimiento de Imágenes",
    descripcion: "Sistema que identifica objetos, personas o textos en imágenes utilizando visión por computadora.",
    categoria: "IA",
    tecnologias: ["Python"],
    frameworks: ["Flask", "OpenCV"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Scraper de Datos Web",
    descripcion: "Herramienta para extraer datos de sitios web y exportarlos en diferentes formatos.",
    categoria: "Utilidad",
    tecnologias: ["Python"],
    frameworks: ["Scrapy", "Flask"],
    basesdedatos: ["SQLite"],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Dashboard de Análisis de Datos",
    descripcion:
      "Panel interactivo para visualizar y analizar grandes conjuntos de datos con gráficos personalizables.",
    categoria: "Análisis de Datos",
    tecnologias: ["Python"],
    frameworks: ["Dash", "Pandas"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Aprendizaje (LMS)",
    descripcion: "Plataforma educativa con cursos, evaluaciones y seguimiento del progreso de estudiantes.",
    categoria: "Educación",
    tecnologias: ["Python"],
    frameworks: ["Django"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Chatbot para Atención al Cliente",
    descripcion: "Bot conversacional que responde preguntas frecuentes y deriva a agentes humanos cuando es necesario.",
    categoria: "IA",
    tecnologias: ["Python"],
    frameworks: ["Flask", "NLTK"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Detector de Fraudes Financieros",
    descripcion: "Sistema que utiliza machine learning para detectar transacciones fraudulentas en tiempo real.",
    categoria: "Seguridad",
    tecnologias: ["Python"],
    frameworks: ["Scikit-learn", "FastAPI"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Generador de Informes Automatizados",
    descripcion: "Herramienta que recopila datos de múltiples fuentes y genera informes personalizados.",
    categoria: "Análisis de Datos",
    tecnologias: ["Python"],
    frameworks: ["Pandas", "Flask"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Monitoreo de Redes",
    descripcion: "Aplicación para supervisar el rendimiento y seguridad de redes con alertas en tiempo real.",
    categoria: "Redes",
    tecnologias: ["Python"],
    frameworks: ["Django", "Celery"],
    basesdedatos: ["InfluxDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Java - 10 proyectos
  {
    titulo: "Sistema de Gestión Hospitalaria",
    descripcion:
      "Plataforma completa para gestionar pacientes, citas, historias clínicas y facturación en centros médicos.",
    categoria: "Salud",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot", "Hibernate"],
    basesdedatos: ["Oracle"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Banca Online",
    descripcion: "Sistema bancario con transferencias, pagos, préstamos y gestión de cuentas con alta seguridad.",
    categoria: "Finanzas",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot", "Spring Security"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Recursos Humanos",
    descripcion: "Plataforma para gestionar empleados, nóminas, vacaciones y evaluaciones de desempeño.",
    categoria: "Negocios",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot", "Hibernate"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Gestión de Bibliotecas",
    descripcion: "Sistema para administrar libros, préstamos, usuarios y reservas en bibliotecas.",
    categoria: "Educación",
    tecnologias: ["Java"],
    frameworks: ["JavaFX", "Hibernate"],
    basesdedatos: ["MySQL"],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Plataforma de E-learning Empresarial",
    descripcion: "Sistema de formación para empresas con cursos, evaluaciones y seguimiento de empleados.",
    categoria: "Educación",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot", "Thymeleaf"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Almacenes",
    descripcion: "Aplicación para controlar inventario, ubicaciones, recepciones y envíos en almacenes.",
    categoria: "Logística",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot", "Hibernate"],
    basesdedatos: ["Oracle"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Monitoreo de Servidores",
    descripcion: "Herramienta para supervisar el rendimiento y estado de servidores con alertas y reportes.",
    categoria: "DevOps",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot", "WebFlux"],
    basesdedatos: ["InfluxDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Proyectos de Construcción",
    descripcion: "Plataforma para gestionar proyectos de construcción, materiales, personal y cronogramas.",
    categoria: "Construcción",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot", "Hibernate"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Gestión de Eventos",
    descripcion: "Sistema para organizar eventos, gestionar asistentes, ubicaciones y programación.",
    categoria: "Eventos",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot", "Thymeleaf"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Editor de Diagramas UML",
    descripcion: "Herramienta para crear y editar diagramas UML con exportación a diferentes formatos.",
    categoria: "Desarrollo",
    tecnologias: ["Java"],
    frameworks: ["JavaFX"],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Gestión de Flotas de Vehículos",
    descripcion: "Aplicación para administrar flotas de vehículos, mantenimiento, combustible y conductores.",
    categoria: "Logística",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot", "Hibernate"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Gestión de Seguros",
    descripcion: "Sistema para gestionar pólizas, clientes, reclamaciones y pagos de seguros.",
    categoria: "Finanzas",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot", "JSF"],
    basesdedatos: ["Oracle"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Análisis de Calidad de Software",
    descripcion: "Herramienta para analizar código fuente y detectar problemas de calidad y seguridad.",
    categoria: "Desarrollo",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },

  // C# - 10 proyectos
  {
    titulo: "Sistema de Gestión Inmobiliaria",
    descripcion: "Plataforma para gestionar propiedades, clientes, contratos y pagos para inmobiliarias.",
    categoria: "Inmobiliaria",
    tecnologias: ["C#"],
    frameworks: ["ASP.NET Core", "Entity Framework"],
    basesdedatos: ["SQL Server"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Videojuego 2D de Plataformas",
    descripcion: "Juego de plataformas con niveles, enemigos, power-ups y sistema de puntuación.",
    categoria: "Juego",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Punto de Venta (POS)",
    descripcion: "Aplicación para gestionar ventas, inventario, clientes y reportes para comercios.",
    categoria: "Negocios",
    tecnologias: ["C#"],
    frameworks: ["WPF", "Entity Framework"],
    basesdedatos: ["SQL Server"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Plataforma de Gestión de Contenido Empresarial",
    descripcion: "Sistema para gestionar documentos, flujos de trabajo y colaboración en empresas.",
    categoria: "Empresarial",
    tecnologias: ["C#"],
    frameworks: ["ASP.NET Core", "Entity Framework"],
    basesdedatos: ["SQL Server"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Realidad Aumentada Educativa",
    descripcion: "Herramienta educativa que utiliza RA para visualizar conceptos complejos de forma interactiva.",
    categoria: "Educación",
    tecnologias: ["C#"],
    frameworks: ["Unity", "ARCore"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Sistema de Gestión de Clínicas Dentales",
    descripcion:
      "Plataforma para administrar pacientes animales, tratamientos, citas y facturación en clínicas dentales.",
    categoria: "Salud",
    tecnologias: ["C#"],
    frameworks: ["ASP.NET Core", "Entity Framework"],
    basesdedatos: ["SQL Server"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Herramienta de Análisis de Código",
    descripcion: "Aplicación que analiza código fuente para detectar problemas, patrones y métricas de calidad.",
    categoria: "Desarrollo",
    tecnologias: ["C#"],
    frameworks: [".NET Core"],
    basesdedatos: ["SQLite"],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Gestión de Gimnasios",
    descripcion: "Plataforma para administrar miembros, clases, entrenadores y pagos en gimnasios.",
    categoria: "Deportes",
    tecnologias: ["C#"],
    frameworks: ["ASP.NET Core", "Entity Framework"],
    basesdedatos: ["SQL Server"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Edición de Audio",
    descripcion: "Herramienta para grabar, editar y procesar audio con efectos y exportación a múltiples formatos.",
    categoria: "Multimedia",
    tecnologias: ["C#"],
    frameworks: ["WPF", "NAudio"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Control de Acceso",
    descripcion: "Aplicación para gestionar accesos a instalaciones mediante tarjetas, biometría o códigos.",
    categoria: "Seguridad",
    tecnologias: ["C#"],
    frameworks: [".NET Core"],
    basesdedatos: ["SQL Server"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Juego de Estrategia en Tiempo Real",
    descripcion: "Videojuego de estrategia con múltiples unidades, recursos y combate en tiempo real.",
    categoria: "Juego",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Sistema de Gestión de Veterinarias",
    descripcion: "Aplicación para administrar pacientes animales, tratamientos, citas y facturación.",
    categoria: "Salud",
    tecnologias: ["C#"],
    frameworks: ["ASP.NET Core", "Entity Framework"],
    basesdedatos: ["SQL Server"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Diseño 3D Simple",
    descripcion: "Herramienta básica para crear y manipular modelos 3D con exportación a formatos estándar.",
    categoria: "Diseño",
    tecnologias: ["C#"],
    frameworks: ["WPF", "Helix Toolkit"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },

  // Proyectos adicionales para nivel Trainee
  {
    titulo: "Calculadora Web",
    descripcion: "Calculadora con operaciones básicas y diseño atractivo implementada con JavaScript.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Lista de Tareas Simple",
    descripcion: "Aplicación para gestionar tareas diarias con funcionalidad para añadir, completar y eliminar.",
    categoria: "Productividad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Reloj Digital",
    descripcion: "Reloj digital con formato de 12/24 horas y posibilidad de cambiar zona horaria.",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Generador de Contraseñas",
    descripcion: "Herramienta para generar contraseñas seguras con opciones personalizables.",
    categoria: "Seguridad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Memoria",
    descripcion: "Juego de emparejar cartas para ejercitar la memoria con diferentes niveles de dificultad.",
    categoria: "Juego",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Conversor de Unidades",
    descripcion: "Herramienta para convertir entre diferentes unidades de medida (longitud, peso, temperatura, etc.).",
    categoria: "Utilidad",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Quiz de Preguntas y Respuestas",
    descripcion: "Juego de preguntas y respuestas con puntuación y diferentes categorías.",
    categoria: "Educación",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
]
