// Definir tipos
import type { ProjectIdea } from "./project-ideas"

// Lista de ideas de proyectos para cubrir diversas combinaciones de filtros
export const combinationProjectIdeas: ProjectIdea[] = [
  // Combinaciones para aplicaciones móviles con diferentes tecnologías
  {
    titulo: "Aplicación de Recetas con React Native",
    descripcion: "Aplicación móvil para buscar, guardar y compartir recetas de cocina con fotos y categorías.",
    categoria: "Alimentación",
    tecnologias: ["JavaScript", "React Native"],
    frameworks: ["Expo"],
    basesdedatos: ["Firebase"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Rastreador de Ejercicios con Flutter",
    descripcion: "Aplicación para registrar actividades físicas, establecer metas y visualizar progreso.",
    categoria: "Salud",
    tecnologias: ["Dart"],
    frameworks: ["Flutter"],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Aplicación de Notas con Kotlin",
    descripcion: "Aplicación para tomar notas con categorías, etiquetas y sincronización en la nube.",
    categoria: "Productividad",
    tecnologias: ["Kotlin"],
    frameworks: ["Android Jetpack"],
    basesdedatos: ["Room"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Lector de Noticias con Swift",
    descripcion: "Aplicación para leer noticias de diferentes fuentes con modo offline y temas personalizables.",
    categoria: "Noticias",
    tecnologias: ["Swift"],
    frameworks: ["SwiftUI"],
    basesdedatos: ["Core Data"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },
  {
    titulo: "Aplicación de Meditación con Xamarin",
    descripcion: "Aplicación multiplataforma para meditación guiada con temporizador y sonidos ambientales.",
    categoria: "Salud",
    tecnologias: ["C#"],
    frameworks: ["Xamarin"],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación Móvil",
  },

  // Combinaciones para aplicaciones de escritorio con diferentes tecnologías
  {
    titulo: "Editor de Texto con Electron",
    descripcion: "Editor de texto con resaltado de sintaxis, autocompletado y soporte para múltiples lenguajes.",
    categoria: "Desarrollo",
    tecnologias: ["JavaScript"],
    frameworks: ["Electron", "React"],
    basesdedatos: ["IndexedDB"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Gestor de Finanzas Personales con JavaFX",
    descripcion: "Aplicación para gestionar ingresos, gastos y presupuestos con gráficos y reportes.",
    categoria: "Finanzas",
    tecnologias: ["Java"],
    frameworks: ["JavaFX"],
    basesdedatos: ["H2"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Reproductor de Música con PyQt",
    descripcion: "Reproductor de música con listas de reproducción, ecualizador y soporte para múltiples formatos.",
    categoria: "Multimedia",
    tecnologias: ["Python"],
    frameworks: ["PyQt"],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Gestor de Contraseñas con WPF",
    descripcion: "Aplicación segura para almacenar y gestionar contraseñas con cifrado y generador integrado.",
    categoria: "Seguridad",
    tecnologias: ["C#"],
    frameworks: ["WPF"],
    basesdedatos: ["SQL Server Express"],
    nivel: "Junior",
    tipo: "Aplicación de Escritorio",
  },
  {
    titulo: "Herramienta de Edición de Imágenes con GTK",
    descripcion: "Editor de imágenes con filtros, recorte, redimensionamiento y ajustes básicos.",
    categoria: "Multimedia",
    tecnologias: ["C++"],
    frameworks: ["GTK"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación de Escritorio",
  },

  // Combinaciones para APIs y backends con diferentes tecnologías
  {
    titulo: "API REST para Blog con Express",
    descripcion: "API para gestionar artículos, comentarios y usuarios de un blog con autenticación JWT.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "API",
  },
  {
    titulo: "API GraphQL con Apollo Server",
    descripcion: "API GraphQL para una aplicación de comercio electrónico con productos, pedidos y usuarios.",
    categoria: "E-commerce",
    tecnologias: ["TypeScript"],
    frameworks: ["Apollo Server"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "API",
  },
  {
    titulo: "API REST con Django REST Framework",
    descripcion: "API para una aplicación de gestión de proyectos con tareas, usuarios y equipos.",
    categoria: "Productividad",
    tecnologias: ["Python"],
    frameworks: ["Django REST Framework"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "API",
  },
  {
    titulo: "API REST con Spring Boot",
    descripcion: "API para un sistema de reservas con autenticación OAuth2 y documentación Swagger.",
    categoria: "Servicios",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "API",
  },
  {
    titulo: "API REST con ASP.NET Core",
    descripcion: "API para una aplicación de gestión de inventario con productos, categorías y proveedores.",
    categoria: "Negocios",
    tecnologias: ["C#"],
    frameworks: ["ASP.NET Core"],
    basesdedatos: ["SQL Server"],
    nivel: "Junior",
    tipo: "API",
  },

  // Combinaciones para aplicaciones web con diferentes bases de datos
  {
    titulo: "Aplicación de Gestión de Tareas con MongoDB",
    descripcion: "Aplicación web para gestionar tareas con categorías, fechas límite y colaboración.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Blogs con PostgreSQL",
    descripcion: "Plataforma de blogs con editor WYSIWYG, comentarios y sistema de usuarios.",
    categoria: "Contenido",
    tecnologias: ["TypeScript"],
    frameworks: ["Next.js"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Comercio Electrónico con MySQL",
    descripcion: "Tienda online con catálogo de productos, carrito de compras y procesamiento de pagos.",
    categoria: "E-commerce",
    tecnologias: ["PHP"],
    frameworks: ["Laravel"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Red Social con Firebase",
    descripcion: "Plataforma social con perfiles, publicaciones, comentarios y mensajería en tiempo real.",
    categoria: "Red Social",
    tecnologias: ["JavaScript"],
    frameworks: ["Vue.js"],
    basesdedatos: ["Firebase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Dashboard Analítico con InfluxDB",
    descripcion: "Panel de control para visualizar métricas y datos de series temporales con gráficos interactivos.",
    categoria: "Análisis de Datos",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["InfluxDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Caché con Redis",
    descripcion: "Aplicación web con sistema de caché para mejorar rendimiento y gestionar sesiones.",
    categoria: "Rendimiento",
    tecnologias: ["JavaScript"],
    frameworks: ["Express"],
    basesdedatos: ["Redis", "MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación con Base de Datos Graph Neo4j",
    descripcion: "Sistema de recomendaciones basado en relaciones entre usuarios y productos usando grafos.",
    categoria: "IA",
    tecnologias: ["JavaScript"],
    frameworks: ["Express", "React"],
    basesdedatos: ["Neo4j"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación con CouchDB",
    descripcion: "Sistema de gestión documental con sincronización offline y replicación.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "PouchDB"],
    basesdedatos: ["CouchDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación con DynamoDB",
    descripcion: "Sistema de comercio electrónico escalable con catálogo de productos y gestión de pedidos.",
    categoria: "E-commerce",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "AWS Lambda"],
    basesdedatos: ["DynamoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación con Cassandra",
    descripcion: "Sistema de registro y análisis de eventos de alta disponibilidad y escalabilidad.",
    categoria: "Análisis de Datos",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot"],
    basesdedatos: ["Cassandra"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Combinaciones para videojuegos con diferentes tecnologías
  {
    titulo: "Juego de Plataformas con Phaser",
    descripcion: "Videojuego de plataformas 2D con niveles, enemigos y coleccionables.",
    categoria: "Plataformas",
    tecnologias: ["JavaScript"],
    frameworks: ["Phaser"],
    basesdedatos: ["LocalStorage"],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Estrategia por Turnos con Unity",
    descripcion: "Videojuego de estrategia por turnos con diferentes unidades y escenarios.",
    categoria: "Estrategia",
    tecnologias: ["C#"],
    frameworks: ["Unity"],
    basesdedatos: ["PlayerPrefs"],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Aventura con Godot",
    descripcion: "Videojuego de aventura con puzzles, diálogos y exploración.",
    categoria: "Aventura",
    tecnologias: ["GDScript"],
    frameworks: ["Godot Engine"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Carreras con Unreal Engine",
    descripcion: "Videojuego de carreras con diferentes vehículos, pistas y modos de juego.",
    categoria: "Carreras",
    tecnologias: ["C++", "Blueprints"],
    frameworks: ["Unreal Engine"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Videojuego",
  },
  {
    titulo: "Juego de Rol con RPG Maker",
    descripcion: "Videojuego de rol con historia, combates por turnos y progresión de personajes.",
    categoria: "RPG",
    tecnologias: ["JavaScript"],
    frameworks: ["RPG Maker MZ"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Videojuego",
  },

  // Combinaciones para aplicaciones de consola con diferentes tecnologías
  {
    titulo: "CLI para Gestión de Tareas con Node.js",
    descripcion: "Herramienta de línea de comandos para gestionar tareas y proyectos desde la terminal.",
    categoria: "Productividad",
    tecnologias: ["JavaScript"],
    frameworks: ["Commander.js"],
    basesdedatos: ["JSON"],
    nivel: "Trainee",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Analizador de Logs con Python",
    descripcion: "Herramienta para analizar y extraer información de archivos de registro con estadísticas.",
    categoria: "Utilidad",
    tecnologias: ["Python"],
    frameworks: ["Click"],
    basesdedatos: ["SQLite"],
    nivel: "Trainee",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Gestor de Finanzas Personales con Rust",
    descripcion: "Aplicación de consola para registrar y analizar gastos e ingresos con reportes.",
    categoria: "Finanzas",
    tecnologias: ["Rust"],
    frameworks: ["Clap"],
    basesdedatos: ["SQLite"],
    nivel: "Junior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Herramienta de Cifrado con Go",
    descripcion: "Utilidad para cifrar y descifrar archivos y mensajes con diferentes algoritmos.",
    categoria: "Seguridad",
    tecnologias: ["Go"],
    frameworks: ["Cobra"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Consola",
  },
  {
    titulo: "Sistema de Backup con PowerShell",
    descripcion: "Script para realizar copias de seguridad automatizadas de archivos y bases de datos.",
    categoria: "Utilidad",
    tecnologias: ["PowerShell"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Aplicación de Consola",
  },

  // Combinaciones para diferentes niveles de experiencia
  {
    titulo: "Portfolio Personal con HTML y CSS",
    descripcion: "Sitio web personal para mostrar proyectos y habilidades con diseño responsive.",
    categoria: "Web",
    tecnologias: ["HTML", "CSS"],
    frameworks: [],
    basesdedatos: [],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Juego de Memoria con JavaScript",
    descripcion: "Juego de emparejar cartas para ejercitar la memoria con diferentes niveles.",
    categoria: "Juego",
    tecnologias: ["HTML", "CSS", "JavaScript"],
    frameworks: [],
    basesdedatos: ["LocalStorage"],
    nivel: "Student",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Blog Personal con Jekyll",
    descripcion: "Blog estático con Jekyll para compartir artículos y tutoriales.",
    categoria: "Contenido",
    tecnologias: ["HTML", "CSS", "Markdown"],
    frameworks: ["Jekyll"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Clima con React",
    descripcion: "Aplicación para consultar el clima actual y pronóstico de diferentes ciudades.",
    categoria: "Utilidad",
    tecnologias: ["JavaScript"],
    frameworks: ["React"],
    basesdedatos: [],
    nivel: "Trainee",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Inventario con MERN",
    descripcion: "Aplicación completa para gestionar productos, categorías, proveedores y ventas.",
    categoria: "Negocios",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Red Social para Desarrolladores",
    descripcion: "Plataforma para que desarrolladores compartan proyectos, conocimientos y colaboren.",
    categoria: "Red Social",
    tecnologias: ["TypeScript"],
    frameworks: ["Next.js"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Combinaciones específicas de tecnologías y frameworks
  {
    titulo: "Aplicación SPA con Vue.js y Vuex",
    descripcion: "Aplicación de página única con gestión de estado centralizada para una experiencia fluida.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["Vue.js", "Vuex"],
    basesdedatos: ["Firebase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación PWA con React y Redux",
    descripcion: "Aplicación web progresiva con funcionalidad offline y experiencia similar a una app nativa.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Redux"],
    basesdedatos: ["IndexedDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación con Angular y NgRx",
    descripcion: "Aplicación web con gestión de estado reactiva y arquitectura modular.",
    categoria: "Web",
    tecnologias: ["TypeScript"],
    frameworks: ["Angular", "NgRx"],
    basesdedatos: ["Firebase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación con Svelte y SvelteKit",
    descripcion: "Aplicación web con enfoque en rendimiento y experiencia de desarrollo simplificada.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["Svelte", "SvelteKit"],
    basesdedatos: ["Supabase"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación con Ruby on Rails",
    descripcion: "Aplicación web completa siguiendo convenciones y mejores prácticas de Rails.",
    categoria: "Web",
    tecnologias: ["Ruby"],
    frameworks: ["Ruby on Rails"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },

  // Combinaciones para aplicaciones fullstack con diferentes stacks
  {
    titulo: "Aplicación Fullstack MERN",
    descripcion: "Aplicación web completa con MongoDB, Express, React y Node.js.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Fullstack",
  },
  {
    titulo: "Aplicación Fullstack PERN",
    descripcion: "Aplicación web completa con PostgreSQL, Express, React y Node.js.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Fullstack",
  },
  {
    titulo: "Aplicación Fullstack MEAN",
    descripcion: "Aplicación web completa con MongoDB, Express, Angular y Node.js.",
    categoria: "Web",
    tecnologias: ["TypeScript"],
    frameworks: ["Angular", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Fullstack",
  },
  {
    titulo: "Aplicación Fullstack MEVN",
    descripcion: "Aplicación web completa con MongoDB, Express, Vue.js y Node.js.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["Vue.js", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Fullstack",
  },
  {
    titulo: "Aplicación Fullstack Django-React",
    descripcion: "Aplicación web completa con Django REST Framework y React.",
    categoria: "Web",
    tecnologias: ["Python", "JavaScript"],
    frameworks: ["Django", "React"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Fullstack",
  },
  {
    titulo: "Aplicación Fullstack Laravel-Vue",
    descripcion: "Aplicación web completa con Laravel y Vue.js.",
    categoria: "Web",
    tecnologias: ["PHP", "JavaScript"],
    frameworks: ["Laravel", "Vue.js"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Fullstack",
  },
  {
    titulo: "Aplicación Fullstack .NET-Angular",
    descripcion: "Aplicación web completa con ASP.NET Core y Angular.",
    categoria: "Web",
    tecnologias: ["C#", "TypeScript"],
    frameworks: ["ASP.NET Core", "Angular"],
    basesdedatos: ["SQL Server"],
    nivel: "Junior",
    tipo: "Fullstack",
  },
  {
    titulo: "Aplicación Fullstack Spring-React",
    descripcion: "Aplicación web completa con Spring Boot y React.",
    categoria: "Web",
    tecnologias: ["Java", "JavaScript"],
    frameworks: ["Spring Boot", "React"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Fullstack",
  },

  // Combinaciones para aplicaciones frontend con diferentes frameworks
  {
    titulo: "Dashboard Administrativo con React",
    descripcion: "Panel de administración con tablas, gráficos y formularios para gestionar datos.",
    categoria: "Web",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Material UI"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Frontend",
  },
  {
    titulo: "Tienda Online Frontend con Vue.js",
    descripcion: "Interfaz de usuario para una tienda online con catálogo, carrito y checkout.",
    categoria: "E-commerce",
    tecnologias: ["JavaScript"],
    frameworks: ["Vue.js", "Vuetify"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Frontend",
  },
  {
    titulo: "Aplicación de Redes Sociales con Angular",
    descripcion: "Interfaz de usuario para una red social con perfiles, publicaciones y mensajería.",
    categoria: "Red Social",
    tecnologias: ["TypeScript"],
    frameworks: ["Angular", "Angular Material"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Frontend",
  },
  {
    titulo: "Aplicación de Música con Svelte",
    descripcion: "Interfaz de usuario para un servicio de streaming de música con reproductor y playlists.",
    categoria: "Multimedia",
    tecnologias: ["JavaScript"],
    frameworks: ["Svelte"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Frontend",
  },
  {
    titulo: "Plataforma Educativa con Ember.js",
    descripcion: "Interfaz de usuario para una plataforma de cursos online con lecciones y evaluaciones.",
    categoria: "Educación",
    tecnologias: ["JavaScript"],
    frameworks: ["Ember.js"],
    basesdedatos: [],
    nivel: "Junior",
    tipo: "Frontend",
  },

  // Combinaciones para aplicaciones backend con diferentes tecnologías
  {
    titulo: "API REST para E-commerce con Node.js",
    descripcion: "Backend para una tienda online con productos, usuarios, pedidos y pagos.",
    categoria: "E-commerce",
    tecnologias: ["JavaScript"],
    frameworks: ["Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Backend",
  },
  {
    titulo: "API GraphQL con Apollo Server",
    descripcion: "Backend con GraphQL para una aplicación de redes sociales con usuarios y publicaciones.",
    categoria: "Red Social",
    tecnologias: ["TypeScript"],
    frameworks: ["Apollo Server"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Backend",
  },
  {
    titulo: "Microservicios con Spring Boot",
    descripcion: "Arquitectura de microservicios para una aplicación empresarial con diferentes dominios.",
    categoria: "Empresarial",
    tecnologias: ["Java"],
    frameworks: ["Spring Boot"],
    basesdedatos: ["MySQL"],
    nivel: "Senior",
    tipo: "Backend",
  },
  {
    titulo: "API REST con Django",
    descripcion: "Backend para una aplicación de gestión de proyectos con tareas y usuarios.",
    categoria: "Productividad",
    tecnologias: ["Python"],
    frameworks: ["Django REST Framework"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Backend",
  },
  {
    titulo: "API REST con Laravel",
    descripcion: "Backend para un sistema de blogs con artículos, comentarios y usuarios.",
    categoria: "Contenido",
    tecnologias: ["PHP"],
    frameworks: ["Laravel"],
    basesdedatos: ["MySQL"],
    nivel: "Junior",
    tipo: "Backend",
  },
  {
    titulo: "API REST con ASP.NET Core",
    descripcion: "Backend para una aplicación de gestión de inventario con productos y categorías.",
    categoria: "Negocios",
    tecnologias: ["C#"],
    frameworks: ["ASP.NET Core"],
    basesdedatos: ["SQL Server"],
    nivel: "Junior",
    tipo: "Backend",
  },
  {
    titulo: "API REST con Go",
    descripcion: "Backend de alto rendimiento para una aplicación de streaming de video.",
    categoria: "Multimedia",
    tecnologias: ["Go"],
    frameworks: ["Gin"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Backend",
  },
  {
    titulo: "API REST con Ruby on Rails",
    descripcion: "Backend para una aplicación de reservas con usuarios, servicios y pagos.",
    categoria: "Servicios",
    tecnologias: ["Ruby"],
    frameworks: ["Ruby on Rails"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Backend",
  },

  // Combinaciones para aplicaciones con tecnologías emergentes
  {
    titulo: "Aplicación Web con WebAssembly",
    descripcion: "Aplicación web de alto rendimiento con componentes críticos implementados en WebAssembly.",
    categoria: "Rendimiento",
    tecnologias: ["Rust", "JavaScript"],
    frameworks: ["React"],
    basesdedatos: ["IndexedDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación Blockchain con Solidity",
    descripcion: "Aplicación descentralizada (dApp) con contratos inteligentes en Ethereum.",
    categoria: "Blockchain",
    tecnologias: ["Solidity", "JavaScript"],
    frameworks: ["React", "Ethers.js"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación de Realidad Aumentada Web",
    descripcion: "Experiencia de realidad aumentada accesible desde el navegador web.",
    categoria: "AR/VR",
    tecnologias: ["JavaScript"],
    frameworks: ["Three.js", "AR.js"],
    basesdedatos: [],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación con Inteligencia Artificial",
    descripcion: "Aplicación que utiliza modelos de IA para análisis de imágenes o procesamiento de lenguaje natural.",
    categoria: "IA",
    tecnologias: ["Python", "JavaScript"],
    frameworks: ["TensorFlow.js", "React"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Aplicación IoT con MQTT",
    descripcion: "Sistema para monitorear y controlar dispositivos IoT con dashboard en tiempo real.",
    categoria: "IoT",
    tecnologias: ["JavaScript", "Python"],
    frameworks: ["React", "Flask"],
    basesdedatos: ["InfluxDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },

  // Combinaciones para diferentes categorías de aplicaciones
  {
    titulo: "Sistema de Gestión de Salud",
    descripcion: "Aplicación para gestionar pacientes, citas, historias clínicas y facturación.",
    categoria: "Salud",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Aprendizaje en Línea",
    descripcion: "Sistema para crear y consumir cursos con videos, cuestionarios y certificados.",
    categoria: "Educación",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión Inmobiliaria",
    descripcion: "Aplicación para gestionar propiedades, clientes, contratos y pagos.",
    categoria: "Inmobiliaria",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión Financiera",
    descripcion: "Aplicación para gestionar presupuestos, inversiones, gastos e informes financieros.",
    categoria: "Finanzas",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Comercio Electrónico",
    descripcion: "Tienda online completa con catálogo, carrito, pagos y gestión de pedidos.",
    categoria: "E-commerce",
    tecnologias: ["JavaScript"],
    frameworks: ["Next.js"],
    basesdedatos: ["MongoDB"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión de Restaurantes",
    descripcion: "Aplicación para gestionar mesas, pedidos, inventario y facturación en restaurantes.",
    categoria: "Hostelería",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Junior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Plataforma de Viajes",
    descripcion: "Sistema para buscar y reservar vuelos, hoteles y actividades con reseñas de usuarios.",
    categoria: "Viajes",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["MongoDB"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
  {
    titulo: "Sistema de Gestión Legal",
    descripcion: "Aplicación para gestionar casos, clientes, documentos y calendarios para bufetes de abogados.",
    categoria: "Legal",
    tecnologias: ["JavaScript"],
    frameworks: ["React", "Express"],
    basesdedatos: ["PostgreSQL"],
    nivel: "Senior",
    tipo: "Aplicación Web",
  },
]

// Exportar las ideas de proyectos
export default combinationProjectIdeas
